CUSTOM_EMOJI_ALIAS = {
    '+1': ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like'],
    '-1': ['thumbsdown', 'no', 'dislike', 'hand'],
    '100': ['score', 'perfect', 'numbers', 'century', 'exam', 'quiz', 'test', 'pass', 'hundred', 'gina linetti'],
    '1234': ['numbers', 'blue-square'],
    '1st_place_medal': ['award', 'winning', 'first'],
    '2nd_place_medal': ['award', 'second'],
    '3rd_place_medal': ['award', 'third'],
    '8ball': ['pool', 'hobby', 'game', 'luck', 'magic'],
    'a': ['red-square', 'alphabet', 'letter'],
    'ab': ['red-square', 'alphabet'],
    'abacus': ['calculation'],
    'abc': ['blue-square', 'alphabet'],
    'abcd': ['blue-square', 'alphabet'],
    'accept': ['ok', 'good', 'chinese', 'kanji', 'agree', 'yes', 'orange-circle'],
    'adult': ['gender-neutral', 'person'],
    'aerial_tramway': ['transportation', 'vehicle', 'ski'],
    'afghanistan': ['af', 'flag', 'nation', 'country', 'banner'],
    'airplane': ['vehicle', 'transportation', 'flight', 'fly'],
    'aland_islands': ['islands', 'flag', 'nation', 'country', 'banner'],
    'alarm_clock': ['time', 'wake'],
    'albania': ['al', 'flag', 'nation', 'country', 'banner'],
    'alembic': ['distilling', 'science', 'experiment', 'chemistry'],
    'algeria': ['dz', 'flag', 'nation', 'country', 'banner'],
    'alien': ['UFO', 'paul', 'weird', 'outer_space'],
    'ambulance': ['health', '911', 'hospital'],
    'american_samoa': ['american', 'ws', 'flag', 'nation', 'country', 'banner'],
    'amphora': ['vase', 'jar'],
    'anchor': ['ship', 'ferry', 'sea', 'boat'],
    'andorra': ['ad', 'flag', 'nation', 'country', 'banner'],
    'angel': ['heaven', 'wings', 'halo'],
    'anger': ['angry', 'mad'],
    'angola': ['ao', 'flag', 'nation', 'country', 'banner'],
    'angry': ['mad', 'face', 'annoyed', 'frustrated'],
    'anguilla': ['ai', 'flag', 'nation', 'country', 'banner'],
    'anguished': ['face', 'stunned', 'nervous'],
    'ant': ['animal', 'insect', 'nature', 'bug'],
    'antarctica': ['aq', 'flag', 'nation', 'country', 'banner'],
    'antigua_barbuda': ['antigua', 'barbuda', 'flag', 'nation', 'country', 'banner'],
    'apple': ['fruit', 'mac', 'school'],
    'aquarius': ['sign', 'purple-square', 'zodiac', 'astrology'],
    'argentina': ['ar', 'flag', 'nation', 'country', 'banner'],
    'aries': ['sign', 'purple-square', 'zodiac', 'astrology'],
    'armenia': ['am', 'flag', 'nation', 'country', 'banner'],
    'arrow_backward': ['blue-square', 'left', 'direction'],
    'arrow_double_down': ['blue-square', 'direction', 'bottom'],
    'arrow_double_up': ['blue-square', 'direction', 'top'],
    'arrow_down': ['blue-square', 'direction', 'bottom'],
    'arrow_down_small': ['blue-square', 'direction', 'bottom'],
    'arrow_forward': ['blue-square', 'right', 'direction', 'play'],
    'arrow_heading_down': ['blue-square', 'direction', 'bottom'],
    'arrow_heading_up': ['blue-square', 'direction', 'top'],
    'arrow_left': ['blue-square', 'previous', 'back'],
    'arrow_lower_left': ['blue-square', 'direction', 'diagonal', 'southwest'],
    'arrow_lower_right': ['blue-square', 'direction', 'diagonal', 'southeast'],
    'arrow_right': ['blue-square', 'next'],
    'arrow_right_hook': ['blue-square', 'return', 'rotate', 'direction'],
    'arrow_up': ['blue-square', 'continue', 'top', 'direction'],
    'arrow_up_down': ['blue-square', 'direction', 'way', 'vertical'],
    'arrow_up_small': ['blue-square', 'triangle', 'direction', 'point', 'forward', 'top'],
    'arrow_upper_left': ['blue-square', 'point', 'direction', 'diagonal', 'northwest'],
    'arrow_upper_right': ['blue-square', 'point', 'direction', 'diagonal', 'northeast'],
    'arrows_clockwise': ['sync', 'cycle', 'round', 'repeat'],
    'arrows_counterclockwise': ['blue-square', 'sync', 'cycle'],
    'art': ['design', 'paint', 'draw', 'colors'],
    'articulated_lorry': ['vehicle', 'cars', 'transportation', 'express'],
    'artificial_satellite': ['communication', 'gps', 'orbit', 'spaceflight', 'NASA', 'ISS'],
    'aruba': ['aw', 'flag', 'nation', 'country', 'banner'],
    'asterisk': ['star', 'keycap'],
    'astonished': ['face', 'xox', 'surprised', 'poisoned'],
    'athletic_shoe': ['shoes', 'sports', 'sneakers'],
    'atm': ['money', 'sales', 'cash', 'blue-square', 'payment', 'bank'],
    'atom_symbol': ['science', 'physics', 'chemistry'],
    'australia': ['au', 'flag', 'nation', 'country', 'banner'],
    'austria': ['at', 'flag', 'nation', 'country', 'banner'],
    'avocado': ['fruit', 'food'],
    'azerbaijan': ['az', 'flag', 'nation', 'country', 'banner'],
    'b': ['red-square', 'alphabet', 'letter'],
    'baby': ['child', 'boy', 'girl', 'toddler'],
    'baby_bottle': ['food', 'container', 'milk'],
    'baby_chick': ['animal', 'chicken', 'bird'],
    'baby_symbol': ['orange-square', 'child'],
    'back': ['arrow', 'words', 'return'],
    'bacon': ['food', 'breakfast', 'pork', 'pig', 'meat'],
    'badger': ['animal', 'nature', 'honey'],
    'badminton': ['sports'],
    'bagel': ['food', 'bread', 'bakery', 'schmear'],
    'baggage_claim': ['blue-square', 'airport', 'transport'],
    'baguette_bread': ['food', 'bread', 'french'],
    'bahamas': ['bs', 'flag', 'nation', 'country', 'banner'],
    'bahrain': ['bh', 'flag', 'nation', 'country', 'banner'],
    'balance_scale': ['law', 'fairness', 'weight'],
    'balloon': ['party', 'celebration', 'birthday', 'circus'],
    'ballot_box': ['election', 'vote'],
    'ballot_box_with_check': ['ok', 'agree', 'confirm', 'black-square', 'vote', 'election', 'yes', 'tick'],
    'bamboo': ['plant', 'nature', 'vegetable', 'panda', 'pine_decoration'],
    'banana': ['fruit', 'food', 'monkey'],
    'bangbang': ['exclamation', 'surprise'],
    'bangladesh': ['bd', 'flag', 'nation', 'country', 'banner'],
    'bank': ['building', 'money', 'sales', 'cash', 'business', 'enterprise'],
    'bar_chart': ['graph', 'presentation', 'stats'],
    'barbados': ['bb', 'flag', 'nation', 'country', 'banner'],
    'barber': ['hair', 'salon', 'style'],
    'baseball': ['sports', 'balls'],
    'basket': ['laundry'],
    'basketball': ['sports', 'balls', 'NBA'],
    'basketball_man': ['sports', 'human'],
    'basketball_woman': ['sports', 'human', 'woman', 'female'],
    'bat': ['animal', 'nature', 'blind', 'vampire'],
    'bath': ['clean', 'shower', 'bathroom'],
    'bathtub': ['clean', 'shower', 'bathroom'],
    'battery': ['power', 'energy', 'sustain'],
    'beach_umbrella': ['weather', 'summer', 'sunny', 'sand', 'mojito'],
    'bear': ['animal', 'nature', 'wild'],
    'bearded_person': ['person', 'bewhiskered'],
    'bed': ['sleep', 'rest'],
    'beer': ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'],
    'beers': ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'],
    'beetle': ['animal', 'insect', 'nature', 'ladybug'],
    'beginner': ['badge', 'shield'],
    'belarus': ['by', 'flag', 'nation', 'country', 'banner'],
    'belgium': ['be', 'flag', 'nation', 'country', 'banner'],
    'belize': ['bz', 'flag', 'nation', 'country', 'banner'],
    'bell': ['sound', 'notification', 'christmas', 'xmas', 'chime'],
    'bellhop_bell': ['service'],
    'benin': ['bj', 'flag', 'nation', 'country', 'banner'],
    'bento': ['food', 'japanese', 'box'],
    'bermuda': ['bm', 'flag', 'nation', 'country', 'banner'],
    'bhutan': ['bt', 'flag', 'nation', 'country', 'banner'],
    'bike': ['sports', 'bicycle', 'exercise', 'hipster'],
    'biking_man': ['sports', 'bike', 'exercise', 'hipster'],
    'biking_woman': ['sports', 'bike', 'exercise', 'hipster', 'woman', 'female'],
    'bikini': ['swimming', 'female', 'woman', 'girl', 'fashion', 'beach', 'summer'],
    'billed_hat': ['cap', 'baseball'],
    'biohazard': ['danger'],
    'bird': ['animal', 'nature', 'fly', 'tweet', 'spring'],
    'birthday': ['food', 'dessert', 'cake'],
    'black_circle': ['shape', 'button', 'round'],
    'black_flag': ['pirate'],
    'black_heart': ['evil'],
    'black_joker': ['poker', 'cards', 'game', 'play', 'magic'],
    'black_large_square': ['shape', 'icon', 'button'],
    'black_medium_small_square': ['icon', 'shape', 'button'],
    'black_medium_square': ['shape', 'button', 'icon'],
    'black_nib': ['pen', 'stationery', 'writing', 'write'],
    'black_small_square': ['shape', 'icon'],
    'black_square_button': ['shape', 'input', 'frame'],
    'blonde_man': ['man', 'male', 'boy', 'blonde', 'guy', 'person'],
    'blonde_woman': ['woman', 'female', 'girl', 'blonde', 'person'],
    'blossom': ['nature', 'flowers', 'yellow'],
    'blowfish': ['animal', 'nature', 'food', 'sea', 'ocean'],
    'blue_book': ['read', 'library', 'knowledge', 'learn', 'study'],
    'blue_car': ['transportation', 'vehicle'],
    'blue_heart': ['love', 'like', 'affection', 'valentines'],
    'blush': ['face', 'smile', 'happy', 'flushed', 'crush', 'embarrassed', 'shy', 'joy'],
    'boar': ['animal', 'nature'],
    'bolivia': ['bo', 'flag', 'nation', 'country', 'banner'],
    'bomb': ['boom', 'explode', 'explosion', 'terrorism'],
    'bone': ['skeleton'],
    'bookmark': ['favorite', 'label', 'save'],
    'bookmark_tabs': ['favorite', 'save', 'order', 'tidy'],
    'books': ['literature', 'library', 'study'],
    'boom': ['bomb', 'explode', 'explosion', 'collision', 'blown'],
    'boot': ['shoes', 'fashion'],
    'bosnia_herzegovina': ['bosnia', 'herzegovina', 'flag', 'nation', 'country', 'banner'],
    'botswana': ['bw', 'flag', 'nation', 'country', 'banner'],
    'bouquet': ['flowers', 'nature', 'spring'],
    'bow_and_arrow': ['sports'],
    'bowing_man': ['man', 'male', 'boy'],
    'bowing_woman': ['woman', 'female', 'girl'],
    'bowl_with_spoon': ['food', 'breakfast', 'cereal', 'oatmeal', 'porridge'],
    'bowling': ['sports', 'fun', 'play'],
    'boxing_glove': ['sports', 'fighting'],
    'boy': ['man', 'male', 'guy', 'teenager'],
    'brain': ['smart', 'intelligent'],
    'brazil': ['br', 'flag', 'nation', 'country', 'banner'],
    'bread': ['food', 'wheat', 'breakfast', 'toast'],
    'breastfeeding': ['nursing', 'baby'],
    'brick': ['bricks'],
    'bride_with_veil': ['couple', 'marriage', 'wedding', 'woman', 'bride'],
    'bridge_at_night': ['photo', 'sanfrancisco'],
    'briefcase': ['business', 'documents', 'work', 'law', 'legal', 'job', 'career'],
    'british_indian_ocean_territory': ['british', 'indian', 'ocean', 'territory', 'flag', 'nation', 'country', 'banner'],
    'british_virgin_islands': ['british', 'virgin', 'islands', 'bvi', 'flag', 'nation', 'country', 'banner'],
    'broccoli': ['fruit', 'food', 'vegetable'],
    'broken_heart': ['sad', 'sorry', 'break', 'heart', 'heartbreak'],
    'broom': ['cleaning', 'sweeping', 'witch'],
    'brunei': ['bn', 'darussalam', 'flag', 'nation', 'country', 'banner'],
    'bug': ['animal', 'insect', 'nature', 'worm'],
    'building_construction': ['wip', 'working', 'progress'],
    'bulb': ['light', 'electricity', 'idea'],
    'bulgaria': ['bg', 'flag', 'nation', 'country', 'banner'],
    'bullettrain_front': ['transportation', 'vehicle', 'speed', 'fast', 'public', 'travel'],
    'bullettrain_side': ['transportation', 'vehicle'],
    'burkina_faso': ['burkina', 'faso', 'flag', 'nation', 'country', 'banner'],
    'burrito': ['food', 'mexican'],
    'burundi': ['bi', 'flag', 'nation', 'country', 'banner'],
    'bus': ['car', 'vehicle', 'transportation'],
    'business_suit_levitating': ['suit', 'business', 'levitate', 'hover', 'jump'],
    'busstop': ['transportation', 'wait'],
    'bust_in_silhouette': ['user', 'person', 'human'],
    'busts_in_silhouette': ['user', 'person', 'human', 'group', 'team'],
    'butterfly': ['animal', 'insect', 'nature', 'caterpillar'],
    'cactus': ['vegetable', 'plant', 'nature'],
    'cake': ['food', 'dessert'],
    'calendar': ['schedule', 'date', 'planning'],
    'call_me_hand': ['hands', 'gesture'],
    'calling': ['iphone', 'incoming'],
    'cambodia': ['kh', 'flag', 'nation', 'country', 'banner'],
    'camel': ['animal', 'nature', 'hot', 'desert', 'hump'],
    'camera': ['gadgets', 'photography'],
    'camera_flash': ['photography', 'gadgets'],
    'cameroon': ['cm', 'flag', 'nation', 'country', 'banner'],
    'camping': ['photo', 'outdoors', 'tent'],
    'canada': ['ca', 'flag', 'nation', 'country', 'banner'],
    'canary_islands': ['canary', 'islands', 'flag', 'nation', 'country', 'banner'],
    'cancer': ['sign', 'zodiac', 'purple-square', 'astrology'],
    'candle': ['fire', 'wax'],
    'candy': ['snack', 'dessert', 'sweet', 'lolly'],
    'canned_food': ['food', 'soup'],
    'canoe': ['boat', 'paddle', 'water', 'ship'],
    'cape_verde': ['cabo', 'verde', 'flag', 'nation', 'country', 'banner'],
    'capital_abcd': ['alphabet', 'words', 'blue-square'],
    'capricorn': ['sign', 'zodiac', 'purple-square', 'astrology'],
    'card_file_box': ['business', 'stationery'],
    'card_index': ['business', 'stationery'],
    'card_index_dividers': ['organizing', 'business', 'stationery'],
    'caribbean_netherlands': ['bonaire', 'flag', 'nation', 'country', 'banner'],
    'carousel_horse': ['photo', 'carnival'],
    'carrot': ['vegetable', 'food', 'orange'],
    'cat': ['animal', 'meow', 'nature', 'pet', 'kitten'],
    'cat2': ['animal', 'meow', 'pet', 'cats'],
    'cayman_islands': ['cayman', 'islands', 'flag', 'nation', 'country', 'banner'],
    'cd': ['technology', 'dvd', 'disk', 'disc', '90s'],
    'central_african_republic': ['central', 'african', 'republic', 'flag', 'nation', 'country', 'banner'],
    'chad': ['td', 'flag', 'nation', 'country', 'banner'],
    'chains': ['lock', 'arrest'],
    'champagne': ['drink', 'wine', 'bottle', 'celebration'],
    'chart': ['green-square', 'graph', 'presentation', 'stats'],
    'chart_with_downwards_trend': ['graph', 'presentation', 'stats', 'recession', 'business', 'economics', 'money', 'sales', 'bad', 'failure'],
    'chart_with_upwards_trend': ['graph', 'presentation', 'stats', 'recovery', 'business', 'economics', 'money', 'sales', 'good', 'success'],
    'checkered_flag': ['contest', 'finishline', 'race', 'gokart'],
    'cheese': ['food', 'chadder'],
    'cherries': ['food', 'fruit'],
    'cherry_blossom': ['nature', 'plant', 'spring', 'flower'],
    'chess_pawn': ['expendable'],
    'chestnut': ['food', 'squirrel'],
    'chicken': ['animal', 'cluck', 'nature', 'bird'],
    'child': ['gender-neutral', 'young'],
    'children_crossing': ['school', 'warning', 'danger', 'sign', 'driving', 'yellow-diamond'],
    'chile': ['flag', 'nation', 'country', 'banner'],
    'chipmunk': ['animal', 'nature', 'rodent', 'squirrel'],
    'chocolate_bar': ['food', 'snack', 'dessert', 'sweet'],
    'chopsticks': ['food'],
    'christmas_island': ['christmas', 'island', 'flag', 'nation', 'country', 'banner'],
    'christmas_tree': ['festival', 'vacation', 'december', 'xmas', 'celebration'],
    'church': ['building', 'religion', 'christ'],
    'cinema': ['blue-square', 'record', 'film', 'movie', 'curtain', 'stage', 'theater'],
    'circus_tent': ['festival', 'carnival', 'party'],
    'city_sunrise': ['photo', 'good morning', 'dawn'],
    'city_sunset': ['photo', 'evening', 'sky', 'buildings'],
    'cityscape': ['photo', 'night life', 'urban'],
    'cl': ['alphabet', 'words', 'red-square'],
    'clamp': ['tool'],
    'clap': ['hands', 'praise', 'applause', 'congrats', 'yay'],
    'clapper': ['movie', 'film', 'record'],
    'classical_building': ['art', 'culture', 'history'],
    'climbing_man': ['sports', 'hobby', 'man', 'male', 'rock'],
    'climbing_woman': ['sports', 'hobby', 'woman', 'female', 'rock'],
    'clinking_glasses': ['beverage', 'drink', 'party', 'alcohol', 'celebrate', 'cheers', 'wine', 'champagne', 'toast'],
    'clipboard': ['stationery', 'documents'],
    'clock1': ['time', 'late', 'early', 'schedule'],
    'clock10': ['time', 'late', 'early', 'schedule'],
    'clock1030': ['time', 'late', 'early', 'schedule'],
    'clock11': ['time', 'late', 'early', 'schedule'],
    'clock1130': ['time', 'late', 'early', 'schedule'],
    'clock12': ['time', 'noon', 'midnight', 'midday', 'late', 'early', 'schedule'],
    'clock1230': ['time', 'late', 'early', 'schedule'],
    'clock130': ['time', 'late', 'early', 'schedule'],
    'clock2': ['time', 'late', 'early', 'schedule'],
    'clock230': ['time', 'late', 'early', 'schedule'],
    'clock3': ['time', 'late', 'early', 'schedule'],
    'clock330': ['time', 'late', 'early', 'schedule'],
    'clock4': ['time', 'late', 'early', 'schedule'],
    'clock430': ['time', 'late', 'early', 'schedule'],
    'clock5': ['time', 'late', 'early', 'schedule'],
    'clock530': ['time', 'late', 'early', 'schedule'],
    'clock6': ['time', 'late', 'early', 'schedule', 'dawn', 'dusk'],
    'clock630': ['time', 'late', 'early', 'schedule'],
    'clock7': ['time', 'late', 'early', 'schedule'],
    'clock730': ['time', 'late', 'early', 'schedule'],
    'clock8': ['time', 'late', 'early', 'schedule'],
    'clock830': ['time', 'late', 'early', 'schedule'],
    'clock9': ['time', 'late', 'early', 'schedule'],
    'clock930': ['time', 'late', 'early', 'schedule'],
    'closed_book': ['read', 'library', 'knowledge', 'textbook', 'learn'],
    'closed_lock_with_key': ['security', 'privacy'],
    'closed_umbrella': ['weather', 'rain', 'drizzle'],
    'cloud': ['weather', 'sky'],
    'cloud_with_lightning': ['weather', 'thunder'],
    'cloud_with_lightning_and_rain': ['weather', 'lightning'],
    'cloud_with_rain': ['weather'],
    'cloud_with_snow': ['weather'],
    'clown_face': ['face'],
    'clubs': ['poker', 'cards', 'magic', 'suits'],
    'cn': ['china', 'chinese', 'prc', 'flag', 'country', 'nation', 'banner'],
    'coat': ['jacket'],
    'cocktail': ['drink', 'drunk', 'alcohol', 'beverage', 'booze', 'mojito'],
    'coconut': ['fruit', 'nature', 'food', 'palm'],
    'cocos_islands': ['cocos', 'keeling', 'islands', 'flag', 'nation', 'country', 'banner'],
    'coffee': ['beverage', 'caffeine', 'latte', 'espresso'],
    'coffin': ['vampire', 'dead', 'die', 'death', 'rip', 'graveyard', 'cemetery', 'casket', 'funeral', 'box'],
    'cold': ['face', 'blue', 'freezing', 'frozen', 'frostbite', 'icicles'],
    'cold_sweat': ['face', 'nervous', 'sweat'],
    'colombia': ['co', 'flag', 'nation', 'country', 'banner'],
    'comet': ['space'],
    'comoros': ['km', 'flag', 'nation', 'country', 'banner'],
    'compass': ['magnetic', 'navigation', 'orienteering'],
    'computer': ['technology', 'laptop', 'screen', 'display', 'monitor'],
    'computer_mouse': ['click'],
    'confetti_ball': ['festival', 'party', 'birthday', 'circus'],
    'confounded': ['face', 'confused', 'sick', 'unwell', 'oops', ':S'],
    'confused': ['face', 'indifference', 'huh', 'weird', 'hmmm', ':/'],
    'congo_brazzaville': ['congo', 'flag', 'nation', 'country', 'banner'],
    'congo_kinshasa': ['congo', 'democratic', 'republic', 'flag', 'nation', 'country', 'banner'],
    'congratulations': ['chinese', 'kanji', 'japanese', 'red-circle'],
    'construction': ['wip', 'progress', 'caution', 'warning'],
    'construction_worker_man': ['male', 'human', 'wip', 'guy', 'build', 'construction', 'worker', 'labor'],
    'construction_worker_woman': ['female', 'human', 'wip', 'build', 'construction', 'worker', 'labor', 'woman'],
    'control_knobs': ['dial'],
    'convenience_store': ['building', 'shopping', 'groceries'],
    'cook_islands': ['cook', 'islands', 'flag', 'nation', 'country', 'banner'],
    'cookie': ['food', 'snack', 'oreo', 'chocolate', 'sweet', 'dessert'],
    'cool': ['words', 'blue-square'],
    'copyright': ['ip', 'license', 'circle', 'law', 'legal'],
    'corn': ['food', 'vegetable', 'plant'],
    'costa_rica': ['costa', 'rica', 'flag', 'nation', 'country', 'banner'],
    'cote_divoire': ['ivory', 'coast', 'flag', 'nation', 'country', 'banner'],
    'couch_and_lamp': ['read', 'chill'],
    'couple': ['pair', 'people', 'human', 'love', 'date', 'dating', 'like', 'affection', 'valentines', 'marriage'],
    'couple_with_heart_man_man': ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
    'couple_with_heart_woman_man': ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
    'couple_with_heart_woman_woman': ['pair', 'love', 'like', 'affection', 'human', 'dating', 'valentines', 'marriage'],
    'couplekiss_man_man': ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
    'couplekiss_man_woman': ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
    'couplekiss_woman_woman': ['pair', 'valentines', 'love', 'like', 'dating', 'marriage'],
    'cow': ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'],
    'cow2': ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'],
    'cowboy_hat_face': ['face', 'cowgirl', 'hat'],
    'crab': ['animal', 'crustacean'],
    'crayon': ['drawing', 'creativity'],
    'credit_card': ['money', 'sales', 'dollar', 'bill', 'payment', 'shopping'],
    'crescent_moon': ['night', 'sleep', 'sky', 'evening', 'magic'],
    'cricket': ['sports'],
    'croatia': ['hr', 'flag', 'nation', 'country', 'banner'],
    'crocodile': ['animal', 'nature', 'reptile', 'lizard', 'alligator'],
    'croissant': ['food', 'bread', 'french'],
    'crossed_fingers': ['good', 'lucky'],
    'crossed_flags': ['japanese', 'nation', 'country', 'border'],
    'crossed_swords': ['weapon'],
    'crown': ['king', 'kod', 'leader', 'royalty', 'lord'],
    'cry': ['face', 'tears', 'sad', 'depressed', 'upset', ':\'('],
    'crying_cat_face': ['animal', 'tears', 'weep', 'sad', 'cats', 'upset', 'cry'],
    'crystal_ball': ['disco', 'party', 'magic', 'circus', 'fortune_teller'],
    'cuba': ['cu', 'flag', 'nation', 'country', 'banner'],
    'cucumber': ['fruit', 'food', 'pickle'],
    'cup_with_straw': ['drink', 'soda'],
    'cupcake': ['food', 'dessert', 'bakery', 'sweet'],
    'cupid': ['love', 'like', 'heart', 'affection', 'valentines'],
    'curacao': ['flag', 'nation', 'country', 'banner'],
    'curling_stone': ['sports'],
    'curly_loop': ['scribble', 'draw', 'shape', 'squiggle'],
    'currency_exchange': ['money', 'sales', 'dollar', 'travel'],
    'curry': ['food', 'spicy', 'hot', 'indian'],
    'custard': ['dessert', 'food'],
    'customs': ['passport', 'border', 'blue-square'],
    'cyclone': ['weather', 'swirl', 'blue', 'cloud', 'vortex', 'spiral', 'whirlpool', 'spin', 'tornado', 'hurricane', 'typhoon'],
    'cyprus': ['cy', 'flag', 'nation', 'country', 'banner'],
    'czech_republic': ['cz', 'flag', 'nation', 'country', 'banner'],
    'dagger': ['weapon'],
    'dancer': ['female', 'girl', 'woman', 'fun'],
    'dancing_men': ['male', 'bunny', 'men', 'boys'],
    'dancing_women': ['female', 'bunny', 'women', 'girls'],
    'dango': ['food', 'dessert', 'sweet', 'japanese', 'barbecue', 'meat'],
    'dark_sunglasses': ['face', 'cool', 'accessories'],
    'dart': ['game', 'play', 'bar', 'target', 'bullseye'],
    'dash': ['wind', 'air', 'fast', 'shoo', 'fart', 'smoke', 'puff'],
    'date': ['calendar', 'schedule'],
    'de': ['german', 'nation', 'flag', 'country', 'banner'],
    'deciduous_tree': ['plant', 'nature'],
    'deer': ['animal', 'nature', 'horns', 'venison'],
    'denmark': ['dk', 'flag', 'nation', 'country', 'banner'],
    'department_store': ['building', 'shopping', 'mall'],
    'derelict_house': ['abandon', 'evict', 'broken', 'building'],
    'desert': ['photo', 'warm', 'saharah'],
    'desert_island': ['photo', 'tropical', 'mojito'],
    'desktop_computer': ['technology', 'computing', 'screen'],
    'diamond_shape_with_a_dot_inside': ['jewel', 'blue', 'gem', 'crystal', 'fancy'],
    'diamonds': ['poker', 'cards', 'magic', 'suits'],
    'disappointed': ['face', 'sad', 'upset', 'depressed', ':('],
    'disappointed_relieved': ['face', 'phew', 'sweat', 'nervous'],
    'dizzy': ['star', 'sparkle', 'shoot', 'magic'],
    'dizzy_face': ['spent', 'unconscious', 'xox', 'dizzy'],
    'djibouti': ['dj', 'flag', 'nation', 'country', 'banner'],
    'dna': ['biologist', 'genetics', 'life'],
    'do_not_litter': ['trash', 'bin', 'garbage', 'circle'],
    'dog': ['animal', 'friend', 'nature', 'woof', 'puppy', 'pet', 'faithful'],
    'dog2': ['animal', 'nature', 'friend', 'doge', 'pet', 'faithful'],
    'dollar': ['money', 'sales', 'bill', 'currency'],
    'dolls': ['japanese', 'toy', 'kimono'],
    'dolphin': ['animal', 'nature', 'fish', 'sea', 'ocean', 'flipper', 'fins', 'beach'],
    'dominica': ['dm', 'flag', 'nation', 'country', 'banner'],
    'dominican_republic': ['dominican', 'republic', 'flag', 'nation', 'country', 'banner'],
    'door': ['house', 'entry', 'exit'],
    'doughnut': ['food', 'dessert', 'snack', 'sweet', 'donut'],
    'dove': ['animal', 'bird'],
    'dragon': ['animal', 'myth', 'nature', 'chinese', 'green'],
    'dragon_face': ['animal', 'myth', 'nature', 'chinese', 'green'],
    'dress': ['clothes', 'fashion', 'shopping'],
    'dromedary_camel': ['animal', 'hot', 'desert', 'hump'],
    'drooling_face': ['face'],
    'droplet': ['water', 'drip', 'faucet', 'spring'],
    'drum': ['music', 'instrument', 'drumsticks', 'snare'],
    'duck': ['animal', 'nature', 'bird', 'mallard'],
    'dumpling': ['food', 'empanada', 'pierogi', 'potsticker'],
    'dvd': ['cd', 'disk', 'disc'],
    'e-mail': ['communication', 'inbox'],
    'eagle': ['animal', 'nature', 'bird'],
    'ear': ['face', 'hear', 'sound', 'listen'],
    'ear_of_rice': ['nature', 'plant'],
    'earth_africa': ['globe', 'world', 'international'],
    'earth_americas': ['globe', 'world', 'USA', 'international'],
    'earth_asia': ['globe', 'world', 'east', 'international'],
    'ecuador': ['ec', 'flag', 'nation', 'country', 'banner'],
    'egg': ['food', 'chicken', 'breakfast'],
    'eggplant': ['vegetable', 'nature', 'food', 'aubergine'],
    'egypt': ['eg', 'flag', 'nation', 'country', 'banner'],
    'eight': ['8', 'blue-square', 'numbers'],
    'eight_pointed_black_star': ['orange-square', 'shape', 'polygon'],
    'eight_spoked_asterisk': ['star', 'sparkle', 'green-square'],
    'eject_button': ['blue-square'],
    'el_salvador': ['el', 'salvador', 'flag', 'nation', 'country', 'banner'],
    'electric_plug': ['charger', 'power'],
    'elephant': ['animal', 'nature', 'nose', 'th', 'circus'],
    'email': ['letter', 'postal', 'inbox', 'communication'],
    'end': ['words', 'arrow'],
    'england': ['flag', 'english'],
    'envelope_with_arrow': ['email', 'communication'],
    'equatorial_guinea': ['equatorial', 'gn', 'flag', 'nation', 'country', 'banner'],
    'eritrea': ['er', 'flag', 'nation', 'country', 'banner'],
    'es': ['spain', 'flag', 'nation', 'country', 'banner'],
    'estonia': ['ee', 'flag', 'nation', 'country', 'banner'],
    'ethiopia': ['et', 'flag', 'nation', 'country', 'banner'],
    'eu': ['european', 'union', 'flag', 'banner'],
    'euro': ['money', 'sales', 'dollar', 'currency'],
    'european_castle': ['building', 'royalty', 'history'],
    'european_post_office': ['building', 'email'],
    'evergreen_tree': ['plant', 'nature'],
    'exclamation': ['heavy_exclamation_mark', 'danger', 'surprise', 'punctuation', 'wow', 'warning'],
    'exploding_head': ['face', 'shocked', 'mind', 'blown'],
    'expressionless': ['face', 'indifferent', '-_-', 'meh', 'deadpan'],
    'eye': ['face', 'look', 'see', 'watch', 'stare'],
    'eyeglasses': ['fashion', 'accessories', 'eyesight', 'nerdy', 'dork', 'geek'],
    'eyes': ['look', 'watch', 'stalk', 'peek', 'see'],
    'face_with_head_bandage': ['injured', 'clumsy', 'bandage', 'hurt'],
    'face_with_thermometer': ['sick', 'temperature', 'thermometer', 'cold', 'fever'],
    'facepunch': ['angry', 'violence', 'fist', 'hit', 'attack', 'hand'],
    'factory': ['building', 'industry', 'pollution', 'smoke'],
    'falkland_islands': ['falkland', 'islands', 'malvinas', 'flag', 'nation', 'country', 'banner'],
    'fallen_leaf': ['nature', 'plant', 'vegetable', 'leaves'],
    'family_man_boy': ['home', 'parent', 'people', 'human', 'child'],
    'family_man_boy_boy': ['home', 'parent', 'people', 'human', 'children'],
    'family_man_girl': ['home', 'parent', 'people', 'human', 'child'],
    'family_man_girl_boy': ['home', 'parent', 'people', 'human', 'children'],
    'family_man_girl_girl': ['home', 'parent', 'people', 'human', 'children'],
    'family_man_man_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_man_boy_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_man_girl': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_man_girl_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_man_girl_girl': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_woman_boy': ['home', 'parents', 'child', 'mom', 'dad', 'father', 'mother', 'people', 'human'],
    'family_man_woman_boy_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_woman_girl': ['home', 'parents', 'people', 'human', 'child'],
    'family_man_woman_girl_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_man_woman_girl_girl': ['home', 'parents', 'people', 'human', 'children'],
    'family_woman_boy': ['home', 'parent', 'people', 'human', 'child'],
    'family_woman_boy_boy': ['home', 'parent', 'people', 'human', 'children'],
    'family_woman_girl': ['home', 'parent', 'people', 'human', 'child'],
    'family_woman_girl_boy': ['home', 'parent', 'people', 'human', 'children'],
    'family_woman_girl_girl': ['home', 'parent', 'people', 'human', 'children'],
    'family_woman_woman_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_woman_woman_boy_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_woman_woman_girl': ['home', 'parents', 'people', 'human', 'children'],
    'family_woman_woman_girl_boy': ['home', 'parents', 'people', 'human', 'children'],
    'family_woman_woman_girl_girl': ['home', 'parents', 'people', 'human', 'children'],
    'faroe_islands': ['faroe', 'islands', 'flag', 'nation', 'country', 'banner'],
    'fast_forward': ['blue-square', 'play', 'speed', 'continue'],
    'fax': ['communication', 'technology'],
    'fearful': ['face', 'scared', 'terrified', 'nervous', 'oops', 'huh'],
    'female_detective': ['human', 'spy', 'detective', 'female', 'woman'],
    'ferris_wheel': ['photo', 'carnival', 'londoneye'],
    'ferry': ['boat', 'ship', 'yacht'],
    'field_hockey': ['sports'],
    'fiji': ['fj', 'flag', 'nation', 'country', 'banner'],
    'file_cabinet': ['filing', 'organizing'],
    'file_folder': ['documents', 'business', 'office'],
    'film_projector': ['video', 'tape', 'record', 'movie'],
    'film_strip': ['movie'],
    'finland': ['fi', 'flag', 'nation', 'country', 'banner'],
    'fire': ['hot', 'cook', 'flame'],
    'fire_engine': ['transportation', 'cars', 'vehicle'],
    'fire_extinguisher': ['quench'],
    'firecracker': ['dynamite', 'boom', 'explode', 'explosion', 'explosive'],
    'fireworks': ['photo', 'festival', 'carnival', 'congratulations'],
    'first_quarter_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'first_quarter_moon_with_face': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'fish': ['animal', 'food', 'nature'],
    'fish_cake': ['food', 'japan', 'sea', 'beach', 'narutomaki', 'pink', 'swirl', 'kamaboko', 'surimi', 'ramen'],
    'fishing_pole_and_fish': ['food', 'hobby', 'summer'],
    'fist': ['fingers', 'hand', 'grasp'],
    'fist_left': ['hand', 'fistbump'],
    'fist_right': ['hand', 'fistbump'],
    'five': ['5', 'numbers', 'blue-square', 'prime'],
    'flags': ['fish', 'japanese', 'koinobori', 'carp', 'banner'],
    'flashlight': ['dark', 'camping', 'sight', 'night'],
    'flat_shoe': ['ballet', 'slip-on', 'slipper'],
    'fleur_de_lis': ['decorative', 'scout'],
    'flight_arrival': ['airport', 'flight', 'boarding'],
    'flight_departure': ['airport', 'flight', 'landing'],
    'floppy_disk': ['oldschool', 'technology', 'save', '90s', '80s'],
    'flower_playing_cards': ['game', 'sunset', 'red'],
    'flushed': ['face', 'blush', 'shy', 'flattered'],
    'flying_disc': ['sports', 'frisbee', 'ultimate'],
    'flying_saucer': ['transportation', 'vehicle', 'ufo'],
    'fog': ['weather'],
    'foggy': ['photo', 'mountain'],
    'foot': ['kick', 'stomp'],
    'football': ['sports', 'balls', 'NFL'],
    'footprints': ['feet', 'tracking', 'walking', 'beach'],
    'fork_and_knife': ['cutlery', 'kitchen'],
    'fortune_cookie': ['food', 'prophecy'],
    'fountain': ['photo', 'summer', 'water', 'fresh'],
    'fountain_pen': ['stationery', 'writing', 'write'],
    'four': ['4', 'numbers', 'blue-square'],
    'four_leaf_clover': ['vegetable', 'plant', 'nature', 'lucky', 'irish'],
    'fox_face': ['animal', 'nature', 'face'],
    'fr': ['banner', 'flag', 'nation', 'france', 'french', 'country'],
    'framed_picture': ['photography'],
    'free': ['blue-square', 'words'],
    'french_guiana': ['french', 'guiana', 'flag', 'nation', 'country', 'banner'],
    'french_polynesia': ['french', 'polynesia', 'flag', 'nation', 'country', 'banner'],
    'french_southern_territories': ['french', 'southern', 'territories', 'flag', 'nation', 'country', 'banner'],
    'fried_egg': ['food', 'breakfast', 'kitchen', 'egg'],
    'fried_shrimp': ['food', 'animal', 'appetizer', 'summer'],
    'fries': ['chips', 'snack', 'fast food'],
    'frog': ['animal', 'nature', 'croak', 'toad'],
    'frowning': ['face', 'aw', 'what'],
    'frowning_face': ['face', 'sad', 'upset', 'frown'],
    'frowning_man': ['male', 'boy', 'man', 'sad', 'depressed', 'discouraged', 'unhappy'],
    'frowning_woman': ['female', 'girl', 'woman', 'sad', 'depressed', 'discouraged', 'unhappy'],
    'fu': ['hand', 'fingers', 'rude', 'middle', 'flipping'],
    'fuelpump': ['gas station', 'petroleum'],
    'full_moon': ['nature', 'yellow', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'full_moon_with_face': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'funeral_urn': ['dead', 'die', 'death', 'rip', 'ashes'],
    'gabon': ['ga', 'flag', 'nation', 'country', 'banner'],
    'gambia': ['gm', 'flag', 'nation', 'country', 'banner'],
    'game_die': ['dice', 'random', 'tabletop', 'play', 'luck'],
    'gear': ['cog'],
    'gem': ['blue', 'ruby', 'diamond', 'jewelry'],
    'gemini': ['sign', 'zodiac', 'purple-square', 'astrology'],
    'georgia': ['ge', 'flag', 'nation', 'country', 'banner'],
    'ghana': ['gh', 'flag', 'nation', 'country', 'banner'],
    'ghost': ['halloween', 'spooky', 'scary'],
    'gibraltar': ['gi', 'flag', 'nation', 'country', 'banner'],
    'gift': ['present', 'birthday', 'christmas', 'xmas'],
    'gift_heart': ['love', 'valentines'],
    'giraffe': ['animal', 'nature', 'spots', 'safari'],
    'girl': ['female', 'woman', 'teenager'],
    'globe_with_meridians': ['earth', 'international', 'world', 'internet', 'interweb', 'i18n'],
    'gloves': ['hands', 'winter', 'clothes'],
    'goal_net': ['sports'],
    'goat': ['animal', 'nature'],
    'goggles': ['eyes', 'protection', 'safety'],
    'golf': ['sports', 'business', 'flag', 'hole', 'summer'],
    'golfing_man': ['sports', 'business'],
    'golfing_woman': ['sports', 'business', 'woman', 'female'],
    'gorilla': ['animal', 'nature', 'circus'],
    'grapes': ['fruit', 'food'],
    'grasshopper': ['animal', 'cricket', 'chirp'],
    'greece': ['gr', 'flag', 'nation', 'country', 'banner'],
    'green_apple': ['fruit', 'nature'],
    'green_book': ['read', 'library', 'knowledge', 'study'],
    'green_heart': ['love', 'like', 'affection', 'valentines'],
    'green_salad': ['food', 'healthy', 'lettuce'],
    'greenland': ['gl', 'flag', 'nation', 'country', 'banner'],
    'grenada': ['gd', 'flag', 'nation', 'country', 'banner'],
    'grey_exclamation': ['surprise', 'punctuation', 'gray', 'wow', 'warning'],
    'grey_question': ['doubts', 'gray', 'huh', 'confused'],
    'grimacing': ['face', 'grimace', 'teeth'],
    'grin': ['face', 'happy', 'smile', 'joy', 'kawaii'],
    'grinning': ['face', 'smile', 'happy', 'joy', ':D', 'grin'],
    'guadeloupe': ['gp', 'flag', 'nation', 'country', 'banner'],
    'guam': ['gu', 'flag', 'nation', 'country', 'banner'],
    'guardsman': ['uk', 'gb', 'british', 'male', 'guy', 'royal'],
    'guardswoman': ['uk', 'gb', 'british', 'female', 'royal', 'woman'],
    'guatemala': ['gt', 'flag', 'nation', 'country', 'banner'],
    'guernsey': ['gg', 'flag', 'nation', 'country', 'banner'],
    'guinea': ['gn', 'flag', 'nation', 'country', 'banner'],
    'guinea_bissau': ['gw', 'bissau', 'flag', 'nation', 'country', 'banner'],
    'guitar': ['music', 'instrument'],
    'gun': ['violence', 'weapon', 'pistol', 'revolver'],
    'guyana': ['gy', 'flag', 'nation', 'country', 'banner'],
    'haircut_man': ['male', 'boy', 'man'],
    'haircut_woman': ['female', 'girl', 'woman'],
    'haiti': ['ht', 'flag', 'nation', 'country', 'banner'],
    'hamburger': ['meat', 'fast food', 'beef', 'cheeseburger', 'mcdonalds', 'burger king'],
    'hammer': ['tools', 'build', 'create'],
    'hammer_and_pick': ['tools', 'build', 'create'],
    'hammer_and_wrench': ['tools', 'build', 'create'],
    'hamster': ['animal', 'nature'],
    'hand_over_mouth': ['face', 'whoops', 'shock', 'surprise'],
    'handbag': ['fashion', 'accessory', 'accessories', 'shopping'],
    'handshake': ['agreement', 'shake'],
    'hash': ['symbol', 'blue-square', 'twitter'],
    'hatched_chick': ['animal', 'chicken', 'baby', 'bird'],
    'hatching_chick': ['animal', 'chicken', 'egg', 'born', 'baby', 'bird'],
    'headphones': ['music', 'score', 'gadgets'],
    'hear_no_evil': ['animal', 'monkey', 'nature'],
    'heart': ['love', 'like', 'valentines'],
    'heart_decoration': ['purple-square', 'love', 'like'],
    'heart_eyes': ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart'],
    'heart_eyes_cat': ['animal', 'love', 'like', 'affection', 'cats', 'valentines', 'heart'],
    'heartbeat': ['love', 'like', 'affection', 'valentines', 'pink', 'heart'],
    'heartpulse': ['like', 'love', 'affection', 'valentines', 'pink'],
    'hearts': ['poker', 'cards', 'magic', 'suits'],
    'heavy_check_mark': ['ok', 'nike', 'answer', 'yes', 'tick'],
    'heavy_division_sign': ['divide', 'math', 'calculation'],
    'heavy_dollar_sign': ['money', 'sales', 'payment', 'currency', 'buck'],
    'heavy_heart_exclamation': ['decoration', 'love'],
    'heavy_minus_sign': ['math', 'calculation', 'subtract', 'less'],
    'heavy_multiplication_x': ['math', 'calculation'],
    'heavy_plus_sign': ['math', 'calculation', 'addition', 'more', 'increase'],
    'hedgehog': ['animal', 'nature', 'spiny'],
    'helicopter': ['transportation', 'vehicle', 'fly'],
    'herb': ['vegetable', 'plant', 'medicine', 'weed', 'grass', 'lawn'],
    'hibiscus': ['plant', 'vegetable', 'flowers', 'beach'],
    'high_brightness': ['sun', 'light'],
    'high_heel': ['fashion', 'shoes', 'female', 'pumps', 'stiletto'],
    'hiking_boot': ['backpacking', 'camping', 'hiking'],
    'hippopotamus': ['animal', 'nature'],
    'hocho': ['knife', 'blade', 'cutlery', 'kitchen', 'weapon'],
    'hole': ['embarrassing'],
    'honduras': ['hn', 'flag', 'nation', 'country', 'banner'],
    'honey_pot': ['bees', 'sweet', 'kitchen'],
    'honeybee': ['animal', 'insect', 'nature', 'bug', 'spring', 'honey'],
    'hong_kong': ['hong', 'kong', 'flag', 'nation', 'country', 'banner'],
    'horse': ['animal', 'brown', 'nature'],
    'horse_racing': ['animal', 'betting', 'competition', 'gambling', 'luck'],
    'hospital': ['building', 'health', 'surgery', 'doctor'],
    'hot': ['face', 'feverish', 'heat', 'red', 'sweating'],
    'hot_pepper': ['food', 'spicy', 'chilli', 'chili'],
    'hotdog': ['food', 'frankfurter'],
    'hotel': ['building', 'accomodation', 'checkin'],
    'hotsprings': ['bath', 'warm', 'relax'],
    'hourglass': ['time', 'clock', 'oldschool', 'limit', 'exam', 'quiz', 'test'],
    'hourglass_flowing_sand': ['oldschool', 'time', 'countdown'],
    'house': ['building', 'home'],
    'house_with_garden': ['home', 'plant', 'nature'],
    'houses': ['buildings', 'photo'],
    'hugs': ['face', 'smile', 'hug'],
    'hungary': ['hu', 'flag', 'nation', 'country', 'banner'],
    'hushed': ['face', 'woo', 'shh'],
    'ice_cream': ['food', 'hot', 'dessert'],
    'ice_hockey': ['sports'],
    'ice_skate': ['sports'],
    'icecream': ['food', 'hot', 'dessert', 'summer'],
    'iceland': ['is', 'flag', 'nation', 'country', 'banner'],
    'id': ['purple-square', 'words'],
    'ideograph_advantage': ['chinese', 'kanji', 'obtain', 'get', 'circle'],
    'imp': ['devil', 'angry', 'horns'],
    'inbox_tray': ['email', 'documents'],
    'incoming_envelope': ['email', 'inbox'],
    'india': ['in', 'flag', 'nation', 'country', 'banner'],
    'indonesia': ['flag', 'nation', 'country', 'banner'],
    'infinity': ['forever'],
    'information_source': ['blue-square', 'alphabet', 'letter'],
    'innocent': ['face', 'angel', 'heaven', 'halo'],
    'interrobang': ['wat', 'punctuation', 'surprise'],
    'iphone': ['technology', 'apple', 'gadgets', 'dial'],
    'iran': ['iran,', 'islamic', 'republic', 'flag', 'nation', 'country', 'banner'],
    'iraq': ['iq', 'flag', 'nation', 'country', 'banner'],
    'ireland': ['ie', 'flag', 'nation', 'country', 'banner'],
    'isle_of_man': ['isle', 'man', 'flag', 'nation', 'country', 'banner'],
    'israel': ['il', 'flag', 'nation', 'country', 'banner'],
    'it': ['italy', 'flag', 'nation', 'country', 'banner'],
    'izakaya_lantern': ['light', 'paper', 'halloween', 'spooky'],
    'jack_o_lantern': ['halloween', 'light', 'pumpkin', 'creepy', 'fall'],
    'jamaica': ['jm', 'flag', 'nation', 'country', 'banner'],
    'japan': ['nation', 'country', 'japanese', 'asia'],
    'japanese_castle': ['photo', 'building'],
    'japanese_goblin': ['red', 'evil', 'mask', 'monster', 'scary', 'creepy', 'japanese', 'goblin'],
    'japanese_ogre': ['monster', 'red', 'mask', 'halloween', 'scary', 'creepy', 'devil', 'demon', 'japanese', 'ogre'],
    'jeans': ['fashion', 'shopping'],
    'jersey': ['je', 'flag', 'nation', 'country', 'banner'],
    'jigsaw': ['interlocking', 'puzzle', 'piece'],
    'jordan': ['jo', 'flag', 'nation', 'country', 'banner'],
    'joy': ['face', 'cry', 'tears', 'weep', 'happy', 'happytears', 'haha'],
    'joy_cat': ['animal', 'cats', 'haha', 'happy', 'tears'],
    'joystick': ['game', 'play'],
    'jp': ['japanese', 'nation', 'flag', 'country', 'banner'],
    'kaaba': ['mecca', 'mosque', 'islam'],
    'kangaroo': ['animal', 'nature', 'australia', 'joey', 'hop', 'marsupial'],
    'kazakhstan': ['kz', 'flag', 'nation', 'country', 'banner'],
    'kenya': ['ke', 'flag', 'nation', 'country', 'banner'],
    'key': ['lock', 'door', 'password'],
    'keyboard': ['technology', 'computer', 'type', 'input', 'text'],
    'keycap_ten': ['numbers', '10', 'blue-square'],
    'kick_scooter': ['vehicle', 'kick', 'razor'],
    'kimono': ['dress', 'fashion', 'women', 'female', 'japanese'],
    'kiribati': ['ki', 'flag', 'nation', 'country', 'banner'],
    'kiss': ['face', 'lips', 'love', 'like', 'affection', 'valentines'],
    'kissing': ['love', 'like', 'face', '3', 'valentines', 'infatuation', 'kiss'],
    'kissing_cat': ['animal', 'cats', 'kiss'],
    'kissing_closed_eyes': ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss'],
    'kissing_heart': ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss'],
    'kissing_smiling_eyes': ['face', 'affection', 'valentines', 'infatuation', 'kiss'],
    'kiwi_fruit': ['fruit', 'food'],
    'koala': ['animal', 'nature'],
    'koko': ['blue-square', 'here', 'katakana', 'japanese', 'destination'],
    'kosovo': ['xk', 'flag', 'nation', 'country', 'banner'],
    'kr': ['south', 'korea', 'nation', 'flag', 'country', 'banner'],
    'kuwait': ['kw', 'flag', 'nation', 'country', 'banner'],
    'kyrgyzstan': ['kg', 'flag', 'nation', 'country', 'banner'],
    'labcoat': ['doctor', 'experiment', 'scientist', 'chemist'],
    'label': ['sale', 'tag'],
    'lacrosse': ['sports', 'ball', 'stick'],
    'laos': ['lao', 'democratic', 'republic', 'flag', 'nation', 'country', 'banner'],
    'large_blue_circle': ['shape', 'icon', 'button'],
    'large_blue_diamond': ['shape', 'jewel', 'gem'],
    'large_orange_diamond': ['shape', 'jewel', 'gem'],
    'last_quarter_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'last_quarter_moon_with_face': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'latin_cross': ['christianity'],
    'latvia': ['lv', 'flag', 'nation', 'country', 'banner'],
    'laughing': ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'glad', 'XD', 'laugh'],
    'leafy_greens': ['food', 'vegetable', 'plant', 'bok choy', 'cabbage', 'kale', 'lettuce'],
    'leaves': ['nature', 'plant', 'tree', 'vegetable', 'grass', 'lawn', 'spring'],
    'lebanon': ['lb', 'flag', 'nation', 'country', 'banner'],
    'ledger': ['notes', 'paper'],
    'left_luggage': ['blue-square', 'travel'],
    'left_right_arrow': ['shape', 'direction', 'horizontal', 'sideways'],
    'left_speech_bubble': ['words', 'message', 'talk', 'chatting'],
    'leftwards_arrow_with_hook': ['back', 'return', 'blue-square', 'undo', 'enter'],
    'leg': ['kick', 'limb'],
    'lemon': ['fruit', 'nature'],
    'leo': ['sign', 'purple-square', 'zodiac', 'astrology'],
    'leopard': ['animal', 'nature'],
    'lesotho': ['ls', 'flag', 'nation', 'country', 'banner'],
    'level_slider': ['scale'],
    'liberia': ['lr', 'flag', 'nation', 'country', 'banner'],
    'libra': ['sign', 'purple-square', 'zodiac', 'astrology'],
    'libya': ['ly', 'flag', 'nation', 'country', 'banner'],
    'liechtenstein': ['li', 'flag', 'nation', 'country', 'banner'],
    'light_rail': ['transportation', 'vehicle'],
    'link': ['rings', 'url'],
    'lion': ['animal', 'nature'],
    'lips': ['mouth', 'kiss'],
    'lipstick': ['female', 'girl', 'fashion', 'woman'],
    'lithuania': ['lt', 'flag', 'nation', 'country', 'banner'],
    'lizard': ['animal', 'nature', 'reptile'],
    'llama': ['animal', 'nature', 'alpaca'],
    'lobster': ['animal', 'nature', 'bisque', 'claws', 'seafood'],
    'lock': ['security', 'password', 'padlock'],
    'lock_with_ink_pen': ['security', 'secret'],
    'lollipop': ['food', 'snack', 'candy', 'sweet'],
    'loop': ['tape', 'cassette'],
    'lotion_bottle': ['moisturizer', 'sunscreen'],
    'loud_sound': ['volume', 'noise', 'noisy', 'speaker', 'broadcast'],
    'loudspeaker': ['volume', 'sound'],
    'love_hotel': ['like', 'affection', 'dating'],
    'love_letter': ['email', 'like', 'affection', 'envelope', 'valentines'],
    'love_you': ['hand', 'fingers', 'gesture'],
    'low_brightness': ['sun', 'afternoon', 'warm', 'summer'],
    'luggage': ['packing', 'travel'],
    'luxembourg': ['lu', 'flag', 'nation', 'country', 'banner'],
    'lying_face': ['face', 'lie', 'pinocchio'],
    'm': ['alphabet', 'blue-circle', 'letter'],
    'macau': ['macao', 'flag', 'nation', 'country', 'banner'],
    'macedonia': ['macedonia,', 'flag', 'nation', 'country', 'banner'],
    'madagascar': ['mg', 'flag', 'nation', 'country', 'banner'],
    'mag': ['search', 'zoom', 'find', 'detective'],
    'mag_right': ['search', 'zoom', 'find', 'detective'],
    'magnet': ['attraction', 'magnetic'],
    'mahjong': ['game', 'play', 'chinese', 'kanji'],
    'mailbox': ['email', 'inbox', 'communication'],
    'mailbox_closed': ['email', 'communication', 'inbox'],
    'mailbox_with_mail': ['email', 'inbox', 'communication'],
    'mailbox_with_no_mail': ['email', 'inbox'],
    'malawi': ['mw', 'flag', 'nation', 'country', 'banner'],
    'malaysia': ['my', 'flag', 'nation', 'country', 'banner'],
    'maldives': ['mv', 'flag', 'nation', 'country', 'banner'],
    'male_detective': ['human', 'spy', 'detective'],
    'mali': ['ml', 'flag', 'nation', 'country', 'banner'],
    'malta': ['mt', 'flag', 'nation', 'country', 'banner'],
    'man': ['mustache', 'father', 'dad', 'guy', 'classy', 'sir', 'moustache'],
    'man_artist': ['painter', 'man', 'human'],
    'man_astronaut': ['space', 'rocket', 'man', 'human'],
    'man_cartwheeling': ['gymnastics'],
    'man_cook': ['chef', 'man', 'human'],
    'man_dancing': ['male', 'boy', 'fun', 'dancer'],
    'man_elf': ['man', 'male'],
    'man_facepalming': ['man', 'male', 'boy', 'disbelief'],
    'man_factory_worker': ['assembly', 'industrial', 'man', 'human'],
    'man_fairy': ['man', 'male'],
    'man_farmer': ['rancher', 'gardener', 'man', 'human'],
    'man_firefighter': ['fireman', 'man', 'human'],
    'man_genie': ['man', 'male'],
    'man_health_worker': ['doctor', 'nurse', 'therapist', 'healthcare', 'man', 'human'],
    'man_in_lotus_position': ['man', 'male', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness'],
    'man_in_steamy_room': ['male', 'man', 'spa', 'steamroom', 'sauna'],
    'man_in_tuxedo': ['couple', 'marriage', 'wedding', 'groom'],
    'man_judge': ['justice', 'court', 'man', 'human'],
    'man_juggling': ['juggle', 'balance', 'skill', 'multitask'],
    'man_mechanic': ['plumber', 'man', 'human', 'wrench'],
    'man_office_worker': ['business', 'manager', 'man', 'human'],
    'man_pilot': ['aviator', 'plane', 'man', 'human'],
    'man_playing_handball': ['sports'],
    'man_playing_water_polo': ['sports', 'pool'],
    'man_scientist': ['biologist', 'chemist', 'engineer', 'physicist', 'man', 'human'],
    'man_shrugging': ['man', 'male', 'boy', 'confused', 'indifferent', 'doubt'],
    'man_singer': ['rockstar', 'entertainer', 'man', 'human'],
    'man_student': ['graduate', 'man', 'human'],
    'man_superhero': ['man', 'male', 'good', 'hero', 'superpowers'],
    'man_supervillain': ['man', 'male', 'evil', 'bad', 'criminal', 'hero', 'superpowers'],
    'man_teacher': ['instructor', 'professor', 'man', 'human'],
    'man_technologist': ['coder', 'developer', 'engineer', 'programmer', 'software', 'man', 'human', 'laptop', 'computer'],
    'man_vampire': ['man', 'male', 'dracula'],
    'man_with_gua_pi_mao': ['male', 'boy', 'chinese'],
    'man_with_turban': ['male', 'indian', 'hinduism', 'arabs'],
    'man_zombie': ['man', 'male', 'dracula', 'undead', 'walking dead'],
    'mango': ['fruit', 'food', 'tropical'],
    'mans_shoe': ['fashion', 'male'],
    'mantelpiece_clock': ['time'],
    'maple_leaf': ['nature', 'plant', 'vegetable', 'ca', 'fall'],
    'marshall_islands': ['marshall', 'islands', 'flag', 'nation', 'country', 'banner'],
    'martial_arts_uniform': ['judo', 'karate', 'taekwondo'],
    'martinique': ['mq', 'flag', 'nation', 'country', 'banner'],
    'mask': ['face', 'sick', 'ill', 'disease'],
    'massage_man': ['male', 'boy', 'man', 'head'],
    'massage_woman': ['female', 'girl', 'woman', 'head'],
    'mauritania': ['mr', 'flag', 'nation', 'country', 'banner'],
    'mauritius': ['mu', 'flag', 'nation', 'country', 'banner'],
    'mayotte': ['yt', 'flag', 'nation', 'country', 'banner'],
    'meat_on_bone': ['good', 'food', 'drumstick'],
    'medal_military': ['award', 'winning', 'army'],
    'medal_sports': ['award', 'winning'],
    'mega': ['sound', 'speaker', 'volume'],
    'melon': ['fruit', 'nature', 'food'],
    'memo': ['write', 'documents', 'stationery', 'pencil', 'paper', 'writing', 'legal', 'exam', 'quiz', 'test', 'study', 'compose'],
    'men_wrestling': ['sports', 'wrestlers'],
    'menorah': ['hanukkah', 'candles', 'jewish'],
    'mens': ['toilet', 'restroom', 'wc', 'blue-square', 'gender', 'male'],
    'mermaid': ['woman', 'female', 'merwoman', 'ariel'],
    'merman': ['man', 'male', 'triton'],
    'metal': ['hand', 'fingers', 'evil_eye', 'sign_of_horns', 'rock_on'],
    'metro': ['transportation', 'blue-square', 'mrt', 'underground', 'tube'],
    'mexico': ['mx', 'flag', 'nation', 'country', 'banner'],
    'microbe': ['amoeba', 'bacteria', 'germs'],
    'micronesia': ['micronesia,', 'federated', 'states', 'flag', 'nation', 'country', 'banner'],
    'microphone': ['sound', 'music', 'PA', 'sing', 'talkshow'],
    'microscope': ['laboratory', 'experiment', 'zoomin', 'science', 'study'],
    'milk_glass': ['beverage', 'drink', 'cow'],
    'milky_way': ['photo', 'space', 'stars'],
    'minibus': ['vehicle', 'car', 'transportation'],
    'minidisc': ['technology', 'record', 'data', 'disk', '90s'],
    'mobile_phone_off': ['mute', 'orange-square', 'silence', 'quiet'],
    'moldova': ['moldova,', 'republic', 'flag', 'nation', 'country', 'banner'],
    'monaco': ['mc', 'flag', 'nation', 'country', 'banner'],
    'money_mouth_face': ['face', 'rich', 'dollar', 'money'],
    'money_with_wings': ['dollar', 'bills', 'payment', 'sale'],
    'moneybag': ['dollar', 'payment', 'coins', 'sale'],
    'mongolia': ['mn', 'flag', 'nation', 'country', 'banner'],
    'monkey': ['animal', 'nature', 'banana', 'circus'],
    'monkey_face': ['animal', 'nature', 'circus'],
    'monocle': ['face', 'stuffy', 'wealthy'],
    'monorail': ['transportation', 'vehicle'],
    'montenegro': ['me', 'flag', 'nation', 'country', 'banner'],
    'montserrat': ['ms', 'flag', 'nation', 'country', 'banner'],
    'moon_cake': ['food', 'autumn'],
    'morocco': ['ma', 'flag', 'nation', 'country', 'banner'],
    'mortar_board': ['school', 'college', 'degree', 'university', 'graduation', 'cap', 'hat', 'legal', 'learn', 'education'],
    'mosque': ['islam', 'worship', 'minaret'],
    'mosquito': ['animal', 'nature', 'insect', 'malaria'],
    'motor_boat': ['ship'],
    'motor_scooter': ['vehicle', 'vespa', 'sasha'],
    'motorcycle': ['race', 'sports', 'fast'],
    'motorway': ['road', 'cupertino', 'interstate', 'highway'],
    'mount_fuji': ['photo', 'mountain', 'nature', 'japanese'],
    'mountain': ['photo', 'nature', 'environment'],
    'mountain_biking_man': ['transportation', 'sports', 'human', 'race', 'bike'],
    'mountain_biking_woman': ['transportation', 'sports', 'human', 'race', 'bike', 'woman', 'female'],
    'mountain_cableway': ['transportation', 'vehicle', 'ski'],
    'mountain_railway': ['transportation', 'vehicle'],
    'mountain_snow': ['photo', 'nature', 'environment', 'winter', 'cold'],
    'mouse': ['animal', 'nature', 'cheese_wedge', 'rodent'],
    'mouse2': ['animal', 'nature', 'rodent'],
    'movie_camera': ['film', 'record'],
    'moyai': ['rock', 'easter island', 'moai'],
    'mozambique': ['mz', 'flag', 'nation', 'country', 'banner'],
    'mrs_claus': ['woman', 'female', 'xmas', 'mother christmas'],
    'muscle': ['arm', 'flex', 'hand', 'summer', 'strong', 'biceps'],
    'mushroom': ['plant', 'vegetable'],
    'musical_keyboard': ['piano', 'instrument', 'compose'],
    'musical_note': ['score', 'tone', 'sound'],
    'musical_score': ['treble', 'clef', 'compose'],
    'mute': ['sound', 'volume', 'silence', 'quiet'],
    'myanmar': ['mm', 'flag', 'nation', 'country', 'banner'],
    'nail_care': ['beauty', 'manicure', 'finger', 'fashion', 'nail'],
    'name_badge': ['fire', 'forbid'],
    'namibia': ['na', 'flag', 'nation', 'country', 'banner'],
    'national_park': ['photo', 'environment', 'nature'],
    'nauru': ['nr', 'flag', 'nation', 'country', 'banner'],
    'nauseated_face': ['face', 'vomit', 'gross', 'green', 'sick', 'throw up', 'ill'],
    'nazar_amulet': ['bead', 'charm'],
    'necktie': ['shirt', 'suitup', 'formal', 'fashion', 'cloth', 'business'],
    'negative_squared_cross_mark': ['x', 'green-square', 'no', 'deny'],
    'nepal': ['np', 'flag', 'nation', 'country', 'banner'],
    'nerd_face': ['face', 'nerdy', 'geek', 'dork'],
    'netherlands': ['nl', 'flag', 'nation', 'country', 'banner'],
    'neutral_face': ['indifference', 'meh', ':|', 'neutral'],
    'new': ['blue-square', 'words', 'start'],
    'new_caledonia': ['new', 'caledonia', 'flag', 'nation', 'country', 'banner'],
    'new_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'new_moon_with_face': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'new_zealand': ['new', 'zealand', 'flag', 'nation', 'country', 'banner'],
    'newspaper': ['press', 'headline'],
    'newspaper_roll': ['press', 'headline'],
    'next_track_button': ['forward', 'next', 'blue-square'],
    'ng': ['blue-square', 'words', 'shape', 'icon'],
    'nicaragua': ['ni', 'flag', 'nation', 'country', 'banner'],
    'niger': ['ne', 'flag', 'nation', 'country', 'banner'],
    'nigeria': ['flag', 'nation', 'country', 'banner'],
    'night_with_stars': ['evening', 'city', 'downtown'],
    'nine': ['blue-square', 'numbers', '9'],
    'niue': ['nu', 'flag', 'nation', 'country', 'banner'],
    'no_bell': ['sound', 'volume', 'mute', 'quiet', 'silent'],
    'no_bicycles': ['cyclist', 'prohibited', 'circle'],
    'no_entry': ['limit', 'security', 'privacy', 'bad', 'denied', 'stop', 'circle'],
    'no_entry_sign': ['forbid', 'stop', 'limit', 'denied', 'disallow', 'circle'],
    'no_good_man': ['male', 'boy', 'man', 'nope'],
    'no_good_woman': ['female', 'girl', 'woman', 'nope'],
    'no_mobile_phones': ['iphone', 'mute', 'circle'],
    'no_mouth': ['face', 'hellokitty'],
    'no_pedestrians': ['rules', 'crossing', 'walking', 'circle'],
    'no_smoking': ['cigarette', 'blue-square', 'smell', 'smoke'],
    'non-potable_water': ['drink', 'faucet', 'tap', 'circle'],
    'norfolk_island': ['norfolk', 'island', 'flag', 'nation', 'country', 'banner'],
    'north_korea': ['north', 'korea', 'nation', 'flag', 'country', 'banner'],
    'northern_mariana_islands': ['northern', 'mariana', 'islands', 'flag', 'nation', 'country', 'banner'],
    'norway': ['no', 'flag', 'nation', 'country', 'banner'],
    'nose': ['smell', 'sniff'],
    'notebook': ['stationery', 'record', 'notes', 'paper', 'study'],
    'notebook_with_decorative_cover': ['classroom', 'notes', 'record', 'paper', 'study'],
    'notes': ['music', 'score'],
    'nut_and_bolt': ['handy', 'tools', 'fix'],
    'o': ['circle', 'round'],
    'o2': ['alphabet', 'red-square', 'letter'],
    'ocean': ['sea', 'water', 'wave', 'nature', 'tsunami', 'disaster'],
    'octopus': ['animal', 'creature', 'ocean', 'sea', 'nature', 'beach'],
    'oden': ['food', 'japanese'],
    'office': ['building', 'bureau', 'work'],
    'oil_drum': ['barrell'],
    'ok': ['good', 'agree', 'yes', 'blue-square'],
    'ok_hand': ['fingers', 'limbs', 'perfect', 'ok', 'okay'],
    'ok_man': ['men', 'boy', 'male', 'blue', 'human', 'man'],
    'ok_woman': ['women', 'girl', 'female', 'pink', 'human', 'woman'],
    'old_key': ['lock', 'door', 'password'],
    'older_adult': ['human', 'elder', 'senior', 'gender-neutral'],
    'older_man': ['human', 'male', 'men', 'old', 'elder', 'senior'],
    'older_woman': ['human', 'female', 'women', 'lady', 'old', 'elder', 'senior'],
    'om': ['hinduism', 'buddhism', 'sikhism', 'jainism'],
    'oman': ['om_symbol', 'flag', 'nation', 'country', 'banner'],
    'on': ['arrow', 'words'],
    'oncoming_automobile': ['car', 'vehicle', 'transportation'],
    'oncoming_bus': ['vehicle', 'transportation'],
    'oncoming_police_car': ['vehicle', 'law', 'legal', 'enforcement', '911'],
    'oncoming_taxi': ['vehicle', 'cars', 'uber'],
    'one': ['blue-square', 'numbers', '1'],
    'open_book': ['book', 'read', 'library', 'knowledge', 'literature', 'learn', 'study'],
    'open_file_folder': ['documents', 'load'],
    'open_hands': ['fingers', 'butterfly', 'hands', 'open'],
    'open_mouth': ['face', 'surprise', 'impressed', 'wow', 'whoa', ':O'],
    'open_umbrella': ['weather', 'spring'],
    'ophiuchus': ['sign', 'purple-square', 'constellation', 'astrology'],
    'orange_book': ['read', 'library', 'knowledge', 'textbook', 'study'],
    'orange_heart': ['love', 'like', 'affection', 'valentines'],
    'orthodox_cross': ['suppedaneum', 'religion'],
    'outbox_tray': ['inbox', 'email'],
    'owl': ['animal', 'nature', 'bird', 'hoot'],
    'ox': ['animal', 'cow', 'beef'],
    'package': ['mail', 'gift', 'cardboard', 'box', 'moving'],
    'page_facing_up': ['documents', 'office', 'paper', 'information'],
    'page_with_curl': ['documents', 'office', 'paper'],
    'pager': ['bbcall', 'oldschool', '90s'],
    'paintbrush': ['drawing', 'creativity', 'art'],
    'pakistan': ['pk', 'flag', 'nation', 'country', 'banner'],
    'palau': ['pw', 'flag', 'nation', 'country', 'banner'],
    'palestinian_territories': ['palestine', 'palestinian', 'territories', 'flag', 'nation', 'country', 'banner'],
    'palm_tree': ['plant', 'vegetable', 'nature', 'summer', 'beach', 'mojito', 'tropical'],
    'palms_up': ['hands', 'gesture', 'cupped', 'prayer'],
    'panama': ['pa', 'flag', 'nation', 'country', 'banner'],
    'pancakes': ['food', 'breakfast', 'flapjacks', 'hotcakes'],
    'panda_face': ['animal', 'nature', 'panda'],
    'paperclip': ['documents', 'stationery'],
    'paperclips': ['documents', 'stationery'],
    'papua_new_guinea': ['papua', 'new', 'guinea', 'flag', 'nation', 'country', 'banner'],
    'paraguay': ['py', 'flag', 'nation', 'country', 'banner'],
    'parasol_on_ground': ['weather', 'summer'],
    'parking': ['cars', 'blue-square', 'alphabet', 'letter'],
    'parrot': ['animal', 'nature', 'bird', 'pirate', 'talk'],
    'part_alternation_mark': ['graph', 'presentation', 'stats', 'business', 'economics', 'bad'],
    'partly_sunny': ['weather', 'nature', 'cloudy', 'morning', 'fall', 'spring'],
    'partying': ['face', 'celebration', 'woohoo'],
    'passenger_ship': ['yacht', 'cruise', 'ferry'],
    'passport_control': ['custom', 'blue-square'],
    'pause_button': ['pause', 'blue-square'],
    'paw_prints': ['animal', 'tracking', 'footprints', 'dog', 'cat', 'pet', 'feet'],
    'peace_symbol': ['hippie'],
    'peach': ['fruit', 'nature', 'food'],
    'peacock': ['animal', 'nature', 'peahen', 'bird'],
    'peanuts': ['food', 'nut'],
    'pear': ['fruit', 'nature', 'food'],
    'pen': ['stationery', 'writing', 'write'],
    'pencil2': ['stationery', 'write', 'paper', 'writing', 'school', 'study'],
    'penguin': ['animal', 'nature'],
    'pensive': ['face', 'sad', 'depressed', 'upset'],
    'performing_arts': ['acting', 'theater', 'drama'],
    'persevere': ['face', 'sick', 'no', 'upset', 'oops'],
    'person_fencing': ['sports', 'fencing', 'sword'],
    'peru': ['pe', 'flag', 'nation', 'country', 'banner'],
    'petri_dish': ['bacteria', 'biology', 'culture', 'lab'],
    'philippines': ['ph', 'flag', 'nation', 'country', 'banner'],
    'phone': ['technology', 'communication', 'dial', 'telephone'],
    'pick': ['tools', 'dig'],
    'pie': ['food', 'dessert', 'pastry'],
    'pig': ['animal', 'oink', 'nature'],
    'pig2': ['animal', 'nature'],
    'pig_nose': ['animal', 'oink'],
    'pill': ['health', 'medicine', 'doctor', 'pharmacy', 'drug'],
    'pineapple': ['fruit', 'nature', 'food'],
    'ping_pong': ['sports', 'pingpong'],
    'pirate_flag': ['skull', 'crossbones', 'flag', 'banner'],
    'pisces': ['purple-square', 'sign', 'zodiac', 'astrology'],
    'pitcairn_islands': ['pitcairn', 'flag', 'nation', 'country', 'banner'],
    'pizza': ['food', 'party'],
    'place_of_worship': ['religion', 'church', 'temple', 'prayer'],
    'plate_with_cutlery': ['food', 'eat', 'meal', 'lunch', 'dinner', 'restaurant'],
    'play_or_pause_button': ['blue-square', 'play', 'pause'],
    'pleading': ['face', 'begging', 'mercy'],
    'point_down': ['fingers', 'hand', 'direction', 'down'],
    'point_left': ['direction', 'fingers', 'hand', 'left'],
    'point_right': ['fingers', 'hand', 'direction', 'right'],
    'point_up': ['hand', 'fingers', 'direction', 'up'],
    'point_up_2': ['fingers', 'hand', 'direction', 'up'],
    'poland': ['pl', 'flag', 'nation', 'country', 'banner'],
    'police_car': ['vehicle', 'cars', 'transportation', 'law', 'legal', 'enforcement'],
    'policeman': ['man', 'police', 'law', 'legal', 'enforcement', 'arrest', '911'],
    'policewoman': ['woman', 'police', 'law', 'legal', 'enforcement', 'arrest', '911', 'female'],
    'poodle': ['dog', 'animal', '101', 'nature', 'pet'],
    'poop': ['hankey', 'shitface', 'fail', 'turd', 'shit'],
    'popcorn': ['food', 'movie theater', 'films', 'snack'],
    'portugal': ['pt', 'flag', 'nation', 'country', 'banner'],
    'post_office': ['building', 'envelope', 'communication'],
    'postal_horn': ['instrument', 'music'],
    'postbox': ['email', 'letter', 'envelope'],
    'potable_water': ['blue-square', 'liquid', 'restroom', 'cleaning', 'faucet'],
    'potato': ['food', 'tuber', 'vegatable', 'starch'],
    'pouch': ['bag', 'accessories', 'shopping'],
    'poultry_leg': ['food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey'],
    'pound': ['british', 'sterling', 'money', 'sales', 'bills', 'uk', 'england', 'currency'],
    'pouting_cat': ['animal', 'cats'],
    'pouting_man': ['male', 'boy', 'man'],
    'pouting_woman': ['female', 'girl', 'woman'],
    'pray': ['please', 'hope', 'wish', 'namaste', 'highfive'],
    'prayer_beads': ['dhikr', 'religious'],
    'pregnant_woman': ['baby'],
    'pretzel': ['food', 'bread', 'twisted'],
    'previous_track_button': ['backward'],
    'prince': ['boy', 'man', 'male', 'crown', 'royal', 'king'],
    'princess': ['girl', 'woman', 'female', 'blond', 'crown', 'royal', 'queen'],
    'printer': ['paper', 'ink'],
    'puerto_rico': ['puerto', 'rico', 'flag', 'nation', 'country', 'banner'],
    'purple_heart': ['love', 'like', 'affection', 'valentines'],
    'purse': ['fashion', 'accessories', 'money', 'sales', 'shopping'],
    'pushpin': ['stationery', 'mark', 'here'],
    'put_litter_in_its_place': ['blue-square', 'sign', 'human', 'info'],
    'qatar': ['qa', 'flag', 'nation', 'country', 'banner'],
    'question': ['doubt', 'confused'],
    'rabbit': ['animal', 'nature', 'pet', 'spring', 'magic', 'bunny'],
    'rabbit2': ['animal', 'nature', 'pet', 'magic', 'spring'],
    'raccoon': ['animal', 'nature'],
    'racehorse': ['animal', 'gamble', 'luck'],
    'racing_car': ['sports', 'race', 'fast', 'formula', 'f1'],
    'radio': ['communication', 'music', 'podcast', 'program'],
    'radio_button': ['input', 'old', 'music', 'circle'],
    'radioactive': ['nuclear', 'danger'],
    'rage': ['angry', 'mad', 'hate', 'despise'],
    'railway_car': ['transportation', 'vehicle'],
    'railway_track': ['train', 'transportation'],
    'rainbow': ['nature', 'happy', 'unicorn_face', 'photo', 'sky', 'spring'],
    'rainbow_flag': ['flag', 'rainbow', 'pride', 'gay', 'lgbt', 'glbt', 'queer', 'homosexual', 'lesbian', 'bisexual', 'transgender'],
    'raised_back_of_hand': ['fingers', 'raised', 'backhand'],
    'raised_eyebrow': ['face', 'distrust', 'scepticism', 'disapproval', 'disbelief', 'surprise'],
    'raised_hand': ['fingers', 'stop', 'highfive', 'palm', 'ban'],
    'raised_hand_with_fingers_splayed': ['hand', 'fingers', 'palm'],
    'raised_hands': ['gesture', 'hooray', 'yea', 'celebration', 'hands'],
    'raising_hand_man': ['male', 'boy', 'man'],
    'raising_hand_woman': ['female', 'girl', 'woman'],
    'ram': ['animal', 'sheep', 'nature'],
    'ramen': ['food', 'japanese', 'noodle', 'chopsticks'],
    'rat': ['animal', 'mouse', 'rodent'],
    'receipt': ['accounting', 'expenses'],
    'record_button': ['blue-square'],
    'recycle': ['arrow', 'environment', 'garbage', 'trash'],
    'red_car': ['red', 'transportation', 'vehicle'],
    'red_circle': ['shape', 'error', 'danger'],
    'red_envelope': ['gift'],
    'registered': ['alphabet', 'circle'],
    'relaxed': ['face', 'blush', 'massage', 'happiness'],
    'relieved': ['face', 'relaxed', 'phew', 'massage', 'happiness'],
    'reminder_ribbon': ['sports', 'cause', 'support', 'awareness'],
    'repeat': ['loop', 'record'],
    'repeat_one': ['blue-square', 'loop'],
    'rescue_worker_helmet': ['construction', 'build'],
    'restroom': ['blue-square', 'toilet', 'refresh', 'wc', 'gender'],
    'reunion': ['flag', 'nation', 'country', 'banner'],
    'revolving_hearts': ['love', 'like', 'affection', 'valentines'],
    'rewind': ['play', 'blue-square'],
    'rhinoceros': ['animal', 'nature', 'horn'],
    'ribbon': ['decoration', 'pink', 'girl', 'bowtie'],
    'rice': ['food', 'china', 'asian'],
    'rice_ball': ['food', 'japanese'],
    'rice_cracker': ['food', 'japanese'],
    'rice_scene': ['photo', 'japan', 'asia', 'tsukimi'],
    'right_anger_bubble': ['caption', 'speech', 'thinking', 'mad'],
    'ring': ['wedding', 'propose', 'marriage', 'valentines', 'diamond', 'fashion', 'jewelry', 'gem', 'engagement'],
    'robot': ['computer', 'machine', 'bot'],
    'rocket': ['launch', 'ship', 'staffmode', 'NASA', 'outer space', 'outer_space', 'fly'],
    'rofl': ['face', 'rolling', 'floor', 'laughing', 'lol', 'haha'],
    'roll_eyes': ['face', 'eyeroll', 'frustrated'],
    'roller_coaster': ['carnival', 'playground', 'photo', 'fun'],
    'romania': ['ro', 'flag', 'nation', 'country', 'banner'],
    'rooster': ['animal', 'nature', 'chicken'],
    'rose': ['flowers', 'valentines', 'love', 'spring'],
    'rosette': ['flower', 'decoration', 'military'],
    'rotating_light': ['police', 'ambulance', '911', 'emergency', 'alert', 'error', 'pinged', 'law', 'legal'],
    'round_pushpin': ['stationery', 'location', 'map', 'here'],
    'rowing_man': ['sports', 'hobby', 'water', 'ship'],
    'rowing_woman': ['sports', 'hobby', 'water', 'ship', 'woman', 'female'],
    'ru': ['russian', 'federation', 'flag', 'nation', 'country', 'banner'],
    'rugby_football': ['sports', 'team'],
    'running_man': ['man', 'walking', 'exercise', 'race', 'running'],
    'running_shirt_with_sash': ['play', 'pageant'],
    'running_woman': ['woman', 'walking', 'exercise', 'race', 'running', 'female'],
    'rwanda': ['rw', 'flag', 'nation', 'country', 'banner'],
    'sa': ['japanese', 'blue-square', 'katakana'],
    'safety_pin': ['diaper'],
    'sagittarius': ['sign', 'zodiac', 'purple-square', 'astrology'],
    'sailboat': ['ship', 'summer', 'transportation', 'water', 'sailing'],
    'sake': ['drink', 'drunk', 'beverage', 'japanese', 'alcohol', 'booze'],
    'salt': ['condiment', 'shaker'],
    'samoa': ['ws', 'flag', 'nation', 'country', 'banner'],
    'san_marino': ['san', 'marino', 'flag', 'nation', 'country', 'banner'],
    'sandal': ['shoes', 'fashion', 'flip flops'],
    'sandwich': ['food', 'lunch', 'bread'],
    'santa': ['festival', 'man', 'male', 'xmas', 'father christmas'],
    'sao_tome_principe': ['sao', 'tome', 'principe', 'flag', 'nation', 'country', 'banner'],
    'satellite': ['communication', 'future', 'radio', 'space'],
    'saudi_arabia': ['flag', 'nation', 'country', 'banner'],
    'sauropod': ['animal', 'nature', 'dinosaur', 'brachiosaurus', 'brontosaurus', 'diplodocus', 'extinct'],
    'saxophone': ['music', 'instrument', 'jazz', 'blues'],
    'scarf': ['neck', 'winter', 'clothes'],
    'school': ['building', 'student', 'education', 'learn', 'teach'],
    'school_satchel': ['student', 'education', 'bag', 'backpack'],
    'scissors': ['stationery', 'cut'],
    'scorpion': ['animal', 'arachnid'],
    'scorpius': ['sign', 'zodiac', 'purple-square', 'astrology', 'scorpio'],
    'scotland': ['flag', 'scottish'],
    'scream': ['face', 'munch', 'scared', 'omg'],
    'scream_cat': ['animal', 'cats', 'munch', 'scared', 'scream'],
    'scroll': ['documents', 'ancient', 'history', 'paper'],
    'seat': ['sit', 'airplane', 'transport', 'bus', 'flight', 'fly'],
    'secret': ['privacy', 'chinese', 'sshh', 'kanji', 'red-circle'],
    'see_no_evil': ['monkey', 'animal', 'nature', 'haha'],
    'seedling': ['plant', 'nature', 'grass', 'lawn', 'spring'],
    'selfie': ['camera', 'phone'],
    'senegal': ['sn', 'flag', 'nation', 'country', 'banner'],
    'serbia': ['rs', 'flag', 'nation', 'country', 'banner'],
    'seven': ['7', 'numbers', 'blue-square', 'prime'],
    'seychelles': ['sc', 'flag', 'nation', 'country', 'banner'],
    'shallow_pan_of_food': ['food', 'cooking', 'casserole', 'paella'],
    'shamrock': ['vegetable', 'plant', 'nature', 'irish', 'clover'],
    'shark': ['animal', 'nature', 'fish', 'sea', 'ocean', 'jaws', 'fins', 'beach'],
    'shaved_ice': ['hot', 'dessert', 'summer'],
    'sheep': ['animal', 'nature', 'wool', 'shipit'],
    'shell': ['nature', 'sea', 'beach'],
    'shield': ['protection', 'security'],
    'shinto_shrine': ['temple', 'japan', 'kyoto'],
    'ship': ['transportation', 'titanic', 'deploy'],
    'shopping': ['mall', 'buy', 'purchase'],
    'shopping_cart': ['trolley'],
    'shower': ['clean', 'water', 'bathroom'],
    'shrimp': ['animal', 'ocean', 'nature', 'seafood'],
    'shushing': ['face', 'quiet', 'shhh'],
    'sierra_leone': ['sierra', 'leone', 'flag', 'nation', 'country', 'banner'],
    'signal_strength': ['blue-square', 'reception', 'phone', 'internet', 'connection', 'wifi', 'bluetooth', 'bars'],
    'singapore': ['sg', 'flag', 'nation', 'country', 'banner'],
    'sint_maarten': ['sint', 'maarten', 'dutch', 'flag', 'nation', 'country', 'banner'],
    'six': ['6', 'numbers', 'blue-square'],
    'six_pointed_star': ['purple-square', 'religion', 'jewish', 'hexagram'],
    'skateboard': ['board'],
    'ski': ['sports', 'winter', 'cold', 'snow'],
    'skier': ['sports', 'winter', 'snow'],
    'skull': ['dead', 'skeleton', 'creepy', 'death'],
    'skull_and_crossbones': ['poison', 'danger', 'deadly', 'scary', 'death', 'pirate', 'evil'],
    'sled': ['sleigh', 'luge', 'toboggan'],
    'sleeping': ['face', 'tired', 'sleepy', 'night', 'zzz'],
    'sleeping_bed': ['bed', 'rest'],
    'sleepy': ['face', 'tired', 'rest', 'nap'],
    'slightly_frowning_face': ['face', 'frowning', 'disappointed', 'sad', 'upset'],
    'slightly_smiling_face': ['face', 'smile'],
    'slot_machine': ['bet', 'gamble', 'vegas', 'fruit machine', 'luck', 'casino'],
    'slovakia': ['sk', 'flag', 'nation', 'country', 'banner'],
    'slovenia': ['si', 'flag', 'nation', 'country', 'banner'],
    'small_airplane': ['flight', 'transportation', 'fly', 'vehicle'],
    'small_blue_diamond': ['shape', 'jewel', 'gem'],
    'small_orange_diamond': ['shape', 'jewel', 'gem'],
    'small_red_triangle': ['shape', 'direction', 'up', 'top'],
    'small_red_triangle_down': ['shape', 'direction', 'bottom'],
    'smile': ['face', 'happy', 'joy', 'funny', 'haha', 'laugh', 'like', ':D', ':)'],
    'smile_cat': ['animal', 'cats', 'smile'],
    'smiley': ['face', 'happy', 'joy', 'haha', ':D', ':)', 'smile', 'funny'],
    'smiley_cat': ['animal', 'cats', 'happy', 'smile'],
    'smiling_face_with_three_hearts': ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'hearts', 'adore'],
    'smiling_imp': ['devil', 'horns'],
    'smirk': ['face', 'smile', 'mean', 'prank', 'smug', 'sarcasm'],
    'smirk_cat': ['animal', 'cats', 'smirk'],
    'smoking': ['kills', 'tobacco', 'cigarette', 'joint', 'smoke'],
    'snail': ['slow', 'animal', 'shell'],
    'snake': ['animal', 'evil', 'nature', 'hiss', 'python'],
    'sneezing_face': ['face', 'gesundheit', 'sneeze', 'sick', 'allergy'],
    'snowboarder': ['sports', 'winter'],
    'snowflake': ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas'],
    'snowman': ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas', 'frozen', 'without_snow'],
    'snowman_with_snow': ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas', 'frozen'],
    'soap': ['bar', 'bathing', 'cleaning', 'lather'],
    'sob': ['face', 'cry', 'tears', 'sad', 'upset', 'depressed'],
    'soccer': ['sports', 'football'],
    'socks': ['stockings', 'clothes'],
    'softball': ['sports', 'balls'],
    'solomon_islands': ['solomon', 'islands', 'flag', 'nation', 'country', 'banner'],
    'somalia': ['so', 'flag', 'nation', 'country', 'banner'],
    'soon': ['arrow', 'words'],
    'sorceress': ['woman', 'female', 'mage', 'witch'],
    'sos': ['help', 'red-square', 'words', 'emergency', '911'],
    'sound': ['volume', 'speaker', 'broadcast'],
    'south_africa': ['south', 'africa', 'flag', 'nation', 'country', 'banner'],
    'south_georgia_south_sandwich_islands': ['south', 'georgia', 'sandwich', 'islands', 'flag', 'nation', 'country', 'banner'],
    'south_sudan': ['south', 'sd', 'flag', 'nation', 'country', 'banner'],
    'space_invader': ['game', 'arcade', 'play'],
    'spades': ['poker', 'cards', 'suits', 'magic'],
    'spaghetti': ['food', 'italian', 'noodle'],
    'sparkle': ['stars', 'green-square', 'awesome', 'good', 'fireworks'],
    'sparkler': ['stars', 'night', 'shine'],
    'sparkles': ['stars', 'shine', 'shiny', 'cool', 'awesome', 'good', 'magic'],
    'sparkling_heart': ['love', 'like', 'affection', 'valentines'],
    'speak_no_evil': ['monkey', 'animal', 'nature', 'omg'],
    'speaker': ['sound', 'volume', 'silence', 'broadcast'],
    'speaking_head': ['user', 'person', 'human', 'sing', 'say', 'talk'],
    'speech_balloon': ['bubble', 'words', 'message', 'talk', 'chatting'],
    'speedboat': ['ship', 'transportation', 'vehicle', 'summer'],
    'spider': ['animal', 'arachnid'],
    'spider_web': ['animal', 'insect', 'arachnid', 'silk'],
    'spiral_calendar': ['date', 'schedule', 'planning'],
    'spiral_notepad': ['memo', 'stationery'],
    'sponge': ['absorbing', 'cleaning', 'porous'],
    'spoon': ['cutlery', 'kitchen', 'tableware'],
    'squid': ['animal', 'nature', 'ocean', 'sea'],
    'sri_lanka': ['sri', 'lanka', 'flag', 'nation', 'country', 'banner'],
    'st_barthelemy': ['saint', 'flag', 'nation', 'country', 'banner'],
    'st_helena': ['saint', 'helena', 'ascension', 'tristan', 'cunha', 'flag', 'nation', 'country', 'banner'],
    'st_kitts_nevis': ['saint', 'kitts', 'nevis', 'flag', 'nation', 'country', 'banner'],
    'st_lucia': ['saint', 'lucia', 'flag', 'nation', 'country', 'banner'],
    'st_pierre_miquelon': ['saint', 'pierre', 'miquelon', 'flag', 'nation', 'country', 'banner'],
    'st_vincent_grenadines': ['saint', 'vincent', 'grenadines', 'flag', 'nation', 'country', 'banner'],
    'stadium': ['photo', 'place', 'sports', 'concert', 'venue'],
    'star': ['night', 'yellow'],
    'star2': ['night', 'sparkle', 'awesome', 'good', 'magic'],
    'star_and_crescent': ['islam'],
    'star_of_david': ['judaism'],
    'star_struck': ['face', 'smile', 'starry', 'eyes', 'grinning'],
    'stars': ['night', 'photo'],
    'station': ['transportation', 'vehicle', 'public'],
    'statue_of_liberty': ['american', 'newyork'],
    'steak': ['food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop'],
    'steam_locomotive': ['transportation', 'vehicle', 'train'],
    'stew': ['food', 'meat', 'soup'],
    'stop_button': ['blue-square'],
    'stop_sign': ['stop'],
    'stopwatch': ['time', 'deadline'],
    'straight_ruler': ['stationery', 'calculate', 'length', 'math', 'school', 'drawing', 'architect', 'sketch'],
    'strawberry': ['fruit', 'food', 'nature'],
    'stuck_out_tongue': ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'tongue'],
    'stuck_out_tongue_closed_eyes': ['face', 'prank', 'playful', 'mischievous', 'smile', 'tongue'],
    'stuck_out_tongue_winking_eye': ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue'],
    'studio_microphone': ['sing', 'recording', 'artist', 'talkshow'],
    'stuffed_flatbread': ['food', 'flatbread', 'stuffed', 'gyro'],
    'sudan': ['sd', 'flag', 'nation', 'country', 'banner'],
    'sun_behind_large_cloud': ['weather'],
    'sun_behind_rain_cloud': ['weather'],
    'sun_behind_small_cloud': ['weather'],
    'sun_with_face': ['nature', 'morning', 'sky'],
    'sunflower': ['nature', 'plant', 'fall'],
    'sunglasses': ['face', 'cool', 'smile', 'summer', 'beach', 'sunglass'],
    'sunny': ['weather', 'nature', 'brightness', 'summer', 'beach', 'spring'],
    'sunrise': ['morning', 'view', 'vacation', 'photo'],
    'sunrise_over_mountains': ['view', 'vacation', 'photo'],
    'surfing_man': ['sports', 'ocean', 'sea', 'summer', 'beach'],
    'surfing_woman': ['sports', 'ocean', 'sea', 'summer', 'beach', 'woman', 'female'],
    'suriname': ['sr', 'flag', 'nation', 'country', 'banner'],
    'sushi': ['food', 'fish', 'japanese', 'rice'],
    'suspension_railway': ['vehicle', 'transportation'],
    'swan': ['animal', 'nature', 'bird'],
    'swaziland': ['sz', 'flag', 'nation', 'country', 'banner'],
    'sweat': ['face', 'hot', 'sad', 'tired', 'exercise'],
    'sweat_drops': ['water', 'drip', 'oops'],
    'sweat_smile': ['face', 'hot', 'happy', 'laugh', 'sweat', 'smile', 'relief'],
    'sweden': ['se', 'flag', 'nation', 'country', 'banner'],
    'sweet_potato': ['food', 'nature'],
    'swimming_man': ['sports', 'exercise', 'human', 'athlete', 'water', 'summer'],
    'swimming_woman': ['sports', 'exercise', 'human', 'athlete', 'water', 'summer', 'woman', 'female'],
    'switzerland': ['ch', 'flag', 'nation', 'country', 'banner'],
    'symbols': ['blue-square', 'music', 'note', 'ampersand', 'percent', 'glyphs', 'characters'],
    'symbols_over_mouth': ['face', 'swearing', 'cursing', 'cussing', 'profanity', 'expletive'],
    'synagogue': ['judaism', 'worship', 'temple', 'jewish'],
    'syria': ['syrian', 'arab', 'republic', 'flag', 'nation', 'country', 'banner'],
    'syringe': ['health', 'hospital', 'drugs', 'blood', 'medicine', 'needle', 'doctor', 'nurse'],
    't-rex': ['animal', 'nature', 'dinosaur', 'tyrannosaurus', 'extinct'],
    'taco': ['food', 'mexican'],
    'tada': ['party', 'congratulations', 'birthday', 'magic', 'circus', 'celebration'],
    'taiwan': ['tw', 'flag', 'nation', 'country', 'banner'],
    'tajikistan': ['tj', 'flag', 'nation', 'country', 'banner'],
    'takeout_box': ['food', 'leftovers'],
    'tanabata_tree': ['plant', 'nature', 'branch', 'summer'],
    'tangerine': ['food', 'fruit', 'nature', 'orange'],
    'tanzania': ['tanzania,', 'united', 'republic', 'flag', 'nation', 'country', 'banner'],
    'taurus': ['purple-square', 'sign', 'zodiac', 'astrology'],
    'taxi': ['uber', 'vehicle', 'cars', 'transportation'],
    'tea': ['drink', 'bowl', 'breakfast', 'green', 'british'],
    'teddy_bear': ['plush', 'stuffed'],
    'telephone_receiver': ['technology', 'communication', 'dial'],
    'telescope': ['stars', 'space', 'zoom', 'science', 'astronomy'],
    'tennis': ['sports', 'balls', 'green'],
    'tent': ['photo', 'camping', 'outdoors'],
    'test_tube': ['chemistry', 'experiment', 'lab', 'science'],
    'thailand': ['th', 'flag', 'nation', 'country', 'banner'],
    'thermometer': ['weather', 'temperature', 'hot', 'cold'],
    'thinking': ['face', 'hmmm', 'think', 'consider'],
    'thought_balloon': ['bubble', 'cloud', 'speech', 'thinking', 'dream'],
    'thread': ['needle', 'sewing', 'spool', 'string'],
    'three': ['3', 'numbers', 'prime', 'blue-square'],
    'ticket': ['event', 'concert', 'pass'],
    'tickets': ['sports', 'concert', 'entrance'],
    'tiger': ['animal', 'cat', 'danger', 'wild', 'nature', 'roar'],
    'tiger2': ['animal', 'nature', 'roar'],
    'timer_clock': ['alarm'],
    'timor_leste': ['timor', 'leste', 'flag', 'nation', 'country', 'banner'],
    'tipping_hand_man': ['male', 'boy', 'man', 'human', 'information'],
    'tipping_hand_woman': ['female', 'girl', 'woman', 'human', 'information'],
    'tired_face': ['sick', 'whine', 'upset', 'frustrated'],
    'tm': ['trademark', 'brand', 'law', 'legal'],
    'togo': ['tg', 'flag', 'nation', 'country', 'banner'],
    'toilet': ['restroom', 'wc', 'washroom', 'bathroom', 'potty'],
    'toilet_paper': ['roll'],
    'tokelau': ['tk', 'flag', 'nation', 'country', 'banner'],
    'tokyo_tower': ['photo', 'japanese'],
    'tomato': ['fruit', 'vegetable', 'nature', 'food'],
    'tonga': ['to', 'flag', 'nation', 'country', 'banner'],
    'tongue': ['mouth', 'playful'],
    'toolbox': ['tools', 'diy', 'fix', 'maintainer', 'mechanic'],
    'tooth': ['teeth', 'dentist'],
    'top': ['words', 'blue-square'],
    'tophat': ['magic', 'gentleman', 'classy', 'circus'],
    'tornado': ['weather', 'cyclone', 'twister'],
    'tr': ['turkey', 'flag', 'nation', 'country', 'banner'],
    'trackball': ['technology', 'trackpad'],
    'tractor': ['vehicle', 'car', 'farming', 'agriculture'],
    'traffic_light': ['transportation', 'signal'],
    'train': ['transportation', 'vehicle', 'carriage', 'public', 'travel'],
    'train2': ['transportation', 'vehicle'],
    'tram': ['transportation', 'vehicle'],
    'triangular_flag_on_post': ['mark', 'milestone', 'place'],
    'triangular_ruler': ['stationery', 'math', 'architect', 'sketch'],
    'trident': ['weapon', 'spear'],
    'trinidad_tobago': ['trinidad', 'tobago', 'flag', 'nation', 'country', 'banner'],
    'triumph': ['face', 'gas', 'phew', 'proud', 'pride'],
    'trolleybus': ['bart', 'transportation', 'vehicle'],
    'trophy': ['win', 'award', 'contest', 'place', 'ftw', 'ceremony'],
    'tropical_drink': ['beverage', 'cocktail', 'summer', 'beach', 'alcohol', 'booze', 'mojito'],
    'tropical_fish': ['animal', 'swim', 'ocean', 'beach', 'nemo'],
    'truck': ['cars', 'transportation'],
    'trumpet': ['music', 'brass'],
    'tshirt': ['fashion', 'cloth', 'casual', 'shirt', 'tee'],
    'tulip': ['flowers', 'plant', 'nature', 'summer', 'spring'],
    'tumbler_glass': ['drink', 'beverage', 'drunk', 'alcohol', 'liquor', 'booze', 'bourbon', 'scotch', 'whisky', 'glass', 'shot'],
    'tunisia': ['tn', 'flag', 'nation', 'country', 'banner'],
    'turkey': ['animal', 'bird'],
    'turkmenistan': ['flag', 'nation', 'country', 'banner'],
    'turks_caicos_islands': ['turks', 'caicos', 'islands', 'flag', 'nation', 'country', 'banner'],
    'turtle': ['animal', 'slow', 'nature', 'tortoise'],
    'tuvalu': ['flag', 'nation', 'country', 'banner'],
    'tv': ['technology', 'program', 'oldschool', 'show', 'television'],
    'twisted_rightwards_arrows': ['blue-square', 'shuffle', 'music', 'random'],
    'two': ['numbers', '2', 'prime', 'blue-square'],
    'two_hearts': ['love', 'like', 'affection', 'valentines', 'heart'],
    'two_men_holding_hands': ['pair', 'couple', 'love', 'like', 'bromance', 'friendship', 'people', 'human'],
    'two_women_holding_hands': ['pair', 'friendship', 'couple', 'love', 'like', 'female', 'people', 'human'],
    'u5272': ['cut', 'divide', 'chinese', 'kanji', 'pink-square'],
    'u5408': ['japanese', 'chinese', 'join', 'kanji', 'red-square'],
    'u55b6': ['japanese', 'opening hours', 'orange-square'],
    'u6307': ['chinese', 'point', 'green-square', 'kanji'],
    'u6708': ['chinese', 'month', 'moon', 'japanese', 'orange-square', 'kanji'],
    'u6709': ['orange-square', 'chinese', 'have', 'kanji'],
    'u6e80': ['full', 'chinese', 'japanese', 'red-square', 'kanji'],
    'u7121': ['nothing', 'chinese', 'kanji', 'japanese', 'orange-square'],
    'u7533': ['chinese', 'japanese', 'kanji', 'orange-square'],
    'u7981': ['kanji', 'japanese', 'chinese', 'forbidden', 'limit', 'restricted', 'red-square'],
    'u7a7a': ['kanji', 'japanese', 'chinese', 'empty', 'sky', 'blue-square'],
    'uganda': ['ug', 'flag', 'nation', 'country', 'banner'],
    'uk': ['united', 'kingdom', 'great', 'britain', 'northern', 'ireland', 'flag', 'nation', 'country', 'banner', 'british', 'UK', 'english', 'england', 'union jack'],
    'ukraine': ['ua', 'flag', 'nation', 'country', 'banner'],
    'umbrella': ['rainy', 'weather', 'spring'],
    'unamused': ['indifference', 'bored', 'straight face', 'serious', 'sarcasm', 'unimpressed', 'skeptical', 'dubious', 'side_eye'],
    'underage': ['18', 'drink', 'pub', 'night', 'minor', 'circle'],
    'unicorn': ['animal', 'nature', 'mystical'],
    'united_arab_emirates': ['united', 'arab', 'emirates', 'flag', 'nation', 'country', 'banner'],
    'united_nations': ['un', 'flag', 'banner'],
    'unlock': ['privacy', 'security'],
    'up': ['blue-square', 'above', 'high'],
    'upside_down_face': ['face', 'flipped', 'silly', 'smile'],
    'uruguay': ['uy', 'flag', 'nation', 'country', 'banner'],
    'us': ['united', 'states', 'america', 'flag', 'nation', 'country', 'banner'],
    'us_virgin_islands': ['virgin', 'islands', 'us', 'flag', 'nation', 'country', 'banner'],
    'uzbekistan': ['uz', 'flag', 'nation', 'country', 'banner'],
    'v': ['fingers', 'ohyeah', 'hand', 'peace', 'victory', 'two'],
    'vanuatu': ['vu', 'flag', 'nation', 'country', 'banner'],
    'vatican_city': ['vatican', 'city', 'flag', 'nation', 'country', 'banner'],
    'venezuela': ['ve', 'bolivarian', 'republic', 'flag', 'nation', 'country', 'banner'],
    'vertical_traffic_light': ['transportation', 'driving'],
    'vhs': ['record', 'video', 'oldschool', '90s', '80s'],
    'vibration_mode': ['orange-square', 'phone'],
    'video_camera': ['film', 'record'],
    'video_game': ['play', 'console', 'nintendo switch', 'controller'],
    'vietnam': ['viet', 'nam', 'flag', 'nation', 'country', 'banner'],
    'violin': ['music', 'instrument', 'orchestra', 'symphony'],
    'virgo': ['sign', 'zodiac', 'purple-square', 'astrology'],
    'volcano': ['photo', 'nature', 'disaster'],
    'volleyball': ['sports', 'balls'],
    'vomiting': ['face', 'sick'],
    'vs': ['words', 'orange-square'],
    'vulcan_salute': ['hand', 'fingers', 'spock', 'star trek'],
    'wales': ['flag', 'welsh'],
    'walking_man': ['human', 'feet', 'steps'],
    'walking_woman': ['human', 'feet', 'steps', 'woman', 'female'],
    'wallis_futuna': ['wallis', 'futuna', 'flag', 'nation', 'country', 'banner'],
    'waning_crescent_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'waning_gibbous_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep', 'waxing_gibbous_moon'],
    'warning': ['exclamation', 'wip', 'alert', 'error', 'problem', 'issue'],
    'wastebasket': ['bin', 'trash', 'rubbish', 'garbage', 'toss'],
    'watch': ['time', 'accessories'],
    'water_buffalo': ['animal', 'nature', 'ox', 'cow'],
    'watermelon': ['fruit', 'food', 'picnic', 'summer'],
    'wave': ['hands', 'gesture', 'goodbye', 'solong', 'farewell', 'hello', 'hi', 'palm'],
    'wavy_dash': ['draw', 'line', 'moustache', 'mustache', 'squiggle', 'scribble'],
    'waxing_crescent_moon': ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep'],
    'waxing_gibbous_moon': ['nature', 'night', 'sky', 'gray', 'twilight', 'planet', 'space', 'evening', 'sleep'],
    'wc': ['toilet', 'restroom', 'blue-square'],
    'weary': ['face', 'tired', 'sleepy', 'sad', 'frustrated', 'upset'],
    'wedding': ['love', 'like', 'affection', 'couple', 'marriage', 'bride', 'groom'],
    'weight_lifting_man': ['sports', 'training', 'exercise'],
    'weight_lifting_woman': ['sports', 'training', 'exercise', 'woman', 'female'],
    'western_sahara': ['western', 'sahara', 'flag', 'nation', 'country', 'banner'],
    'whale': ['animal', 'nature', 'sea', 'ocean'],
    'whale2': ['animal', 'nature', 'sea', 'ocean'],
    'wheel_of_dharma': ['hinduism', 'buddhism', 'sikhism', 'jainism'],
    'wheelchair': ['blue-square', 'disabled', 'a11y', 'accessibility'],
    'white_check_mark': ['green-square', 'ok', 'agree', 'vote', 'election', 'answer', 'tick'],
    'white_circle': ['shape', 'round'],
    'white_flag': ['losing', 'loser', 'lost', 'surrender', 'give up', 'fail'],
    'white_flower': ['japanese', 'spring'],
    'white_large_square': ['shape', 'icon', 'stone', 'button'],
    'white_medium_small_square': ['shape', 'stone', 'icon', 'button'],
    'white_medium_square': ['shape', 'stone', 'icon'],
    'white_small_square': ['shape', 'icon'],
    'white_square_button': ['shape', 'input'],
    'wilted_flower': ['plant', 'nature', 'flower'],
    'wind_chime': ['nature', 'ding', 'spring', 'bell'],
    'wind_face': ['gust', 'air'],
    'wine_glass': ['wine', 'drink', 'beverage', 'drunk', 'alcohol', 'booze'],
    'wink': ['face', 'happy', 'mischievous', 'secret', ';)', 'smile', 'eye'],
    'wizard': ['man', 'male', 'mage', 'sorcerer'],
    'wolf': ['animal', 'nature', 'wild'],
    'woman': ['female', 'girls', 'lady'],
    'woman_artist': ['painter', 'woman', 'human'],
    'woman_astronaut': ['space', 'rocket', 'woman', 'human'],
    'woman_cartwheeling': ['gymnastics'],
    'woman_cook': ['chef', 'woman', 'human'],
    'woman_elf': ['woman', 'female'],
    'woman_facepalming': ['woman', 'female', 'girl', 'disbelief'],
    'woman_factory_worker': ['assembly', 'industrial', 'woman', 'human'],
    'woman_fairy': ['woman', 'female'],
    'woman_farmer': ['rancher', 'gardener', 'woman', 'human'],
    'woman_firefighter': ['fireman', 'woman', 'human'],
    'woman_genie': ['woman', 'female'],
    'woman_health_worker': ['doctor', 'nurse', 'therapist', 'healthcare', 'woman', 'human'],
    'woman_in_lotus_position': ['woman', 'female', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness'],
    'woman_in_steamy_room': ['female', 'woman', 'spa', 'steamroom', 'sauna'],
    'woman_judge': ['justice', 'court', 'woman', 'human'],
    'woman_juggling': ['juggle', 'balance', 'skill', 'multitask'],
    'woman_mechanic': ['plumber', 'woman', 'human', 'wrench'],
    'woman_office_worker': ['business', 'manager', 'woman', 'human'],
    'woman_pilot': ['aviator', 'plane', 'woman', 'human'],
    'woman_playing_handball': ['sports'],
    'woman_playing_water_polo': ['sports', 'pool'],
    'woman_scientist': ['biologist', 'chemist', 'engineer', 'physicist', 'woman', 'human'],
    'woman_shrugging': ['woman', 'female', 'girl', 'confused', 'indifferent', 'doubt'],
    'woman_singer': ['rockstar', 'entertainer', 'woman', 'human'],
    'woman_student': ['graduate', 'woman', 'human'],
    'woman_superhero': ['woman', 'female', 'good', 'heroine', 'superpowers'],
    'woman_supervillain': ['woman', 'female', 'evil', 'bad', 'criminal', 'heroine', 'superpowers'],
    'woman_teacher': ['instructor', 'professor', 'woman', 'human'],
    'woman_technologist': ['coder', 'developer', 'engineer', 'programmer', 'software', 'woman', 'human', 'laptop', 'computer'],
    'woman_vampire': ['woman', 'female'],
    'woman_with_headscarf': ['female', 'hijab', 'mantilla', 'tichel'],
    'woman_with_turban': ['female', 'indian', 'hinduism', 'arabs', 'woman'],
    'woman_zombie': ['woman', 'female', 'undead', 'walking dead'],
    'womans_clothes': ['fashion', 'shopping_bags', 'female'],
    'womans_hat': ['fashion', 'accessories', 'female', 'lady', 'spring'],
    'women_wrestling': ['sports', 'wrestlers'],
    'womens': ['purple-square', 'woman', 'female', 'toilet', 'loo', 'restroom', 'gender'],
    'woozy': ['face', 'dizzy', 'intoxicated', 'tipsy', 'wavy'],
    'world_map': ['location', 'direction'],
    'worried': ['face', 'concern', 'nervous', ':('],
    'wrench': ['tools', 'diy', 'ikea', 'fix', 'maintainer'],
    'writing_hand': ['lower_left_ballpoint_pen', 'stationery', 'write', 'compose'],
    'x': ['no', 'delete', 'remove', 'cancel', 'red'],
    'yarn': ['ball', 'crochet', 'knit'],
    'yellow_heart': ['love', 'like', 'affection', 'valentines'],
    'yemen': ['ye', 'flag', 'nation', 'country', 'banner'],
    'yen': ['money', 'sales', 'japanese', 'dollar', 'currency'],
    'yin_yang': ['balance'],
    'yum': ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', 'nom', 'delicious', 'savouring'],
    'zambia': ['zm', 'flag', 'nation', 'country', 'banner'],
    'zany': ['face', 'goofy', 'crazy'],
    'zap': ['thunder', 'weather', 'lightning bolt', 'fast'],
    'zebra': ['animal', 'nature', 'stripes', 'safari'],
    'zero': ['0', 'numbers', 'blue-square', 'null'],
    'zimbabwe': ['zw', 'flag', 'nation', 'country', 'banner'],
    'zipper_mouth_face': ['face', 'sealed', 'zipper', 'secret'],
    'zzz': ['sleepy', 'tired', 'dream'],
}
